GouvernementFR/dsfr

- src/follow/.package.yml
- src/follow/example/index.ejs
- src/follow/example/samples/newsletter-only-form.ejs
- src/follow/styles/_module.scss
- src/follow/templates/ejs/follow.ejs
changement nom du composant en français
Retrait des gutters
Ajout de l'exemple Lettre info seule avec formulaire
> fix(follow): corrections mineures [DS-1915]

- src/share/.package.yml
- src/share/example/index.ejs
- src/share/example/samples/share-default.ejs
- src/share/templates/ejs/share-link.ejs
- src/share/templates/ejs/share.ejs
Correction template ejs
Nom du composant devient "Partage"
> fix(share): correction template ejs et nom du composant [DS-510]

- src/follow/styles/_module.scss
- src/follow/styles/_schemes.scss
fix border-radius en SM
separateur en box shadow plutot que before
> fix(follow): séparateur en box shadow [DS-1915]

- src/core/styles/reset/settings/_font-face.scss
- src/core/styles/reset/tools/_font-face.scss
Ajout de la propriété font-display: swap sur les fonts
> fix(core): font-display swap par défaut [DS-1802]

- src/core/styles/reset/module/_body.scss
- src/core/styles/reset/module/_inputs.scss
Changement de la valeur du text-rendering pour un meilleur rendu de la font marianne
> fix(core): text-rendering en optimizeLegibility [DS-1834]

- src/core/style/typography/tool/_build.scss
> fix(core): style text--md [DS-1851]

- CONTRIBUTING.md
- package.json
- src/core/example/favicon/index.ejs
- tool/example/example.ejs
> fix(favicon): chemin vers dist

- src/component/link/style/tool/_disabled.scss
> fix(link): input type submit désactivé [DS-1994]

- src/core/style/typography/tool/_build.scss
- src/core/template/ejs/typography/paragraph.ejs
> fix(core): exemple texte taille md [DS-1851]

- src/core/example/icon/index.ejs
- src/core/icon/svg/logout-box-r-fill.svg
- src/core/icon/svg/logout-box-r-line.svg
A merger après la refacto ejs #76
> feat(icon): ajout icon logout [DS-2128]

- package.json
- tool/test/pa11y.js
- yarn.lock
stylelint dépendance to latest to fix :autofill lint
> fix: pa11y hide disable elements & fix lint dependance [DS-2177]

- src/component/radio/style/module/_rich.scss
- src/component/radio/style/scheme/_rich.scss
- src/component/radio/template/ejs/radio.ejs
radio__img devient radio-rich__img
bordure sur l'image plutot que le after du label
> fix(radio): bordure sur la classe radio-rich__img

- src/component/link/style/tool/_icon.scss
- src/component/logo/style/_module.scss
- src/component/logo/style/_scheme.scss
- src/component/radio/style/module/_rich.scss
- src/core/style/function/_encoding.scss
radios riche taille image
centrage icone seule
> fix: bug legacy IE [DS-1088]

- README.md
- src/core/template/ejs/favicon/favicon.ejs
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color
> feat(core): ajout meta theme-color dans favicon [DS-2231]

- src/component/tab/example/index.ejs
- src/component/tab/example/sample/tabs-default.ejs
- src/component/tab/style/_module.scss
- src/component/tab/template/ejs/tabs.ejs
Agrandi le groupe d'onglet à 100% de la largeur de l'écran en mobile
> feat(tab): ajout modifieur viewport-width [DS-2075]

- src/component/link/example/index.ejs
- src/component/link/template/ejs/link.ejs
- src/component/pagination/template/ejs/item.ejs
- src/component/share/template/ejs/share-link.ejs
- src/component/tag/template/ejs/tag.ejs
Sur les liens <a> désactivés, il convient d'ajouter role='link' et aria-disabled='true'
> fix(link, tag, pagination, share): role & aria link disabled [DS-2274]

- src/component/toggle/script/toggle/toggle-status-label.js
- src/core/script/api/engine.js
- src/core/script/api/font-swap/font-swap.js
- src/core/script/api/register/instance.js
> feat(core): ajout du module font-swap [DS-2272]

- src/component/alert/example/index.ejs
- src/component/alert/example/sample/alert-dismissable.ejs
…rmable sur l'alerte dynamique
> refactor(alert): alerte dynamique refermable

- src/core/template/ejs/media/img.ejs
> fix(core): faute dans le texte alternatif [DS-2153]

- src/component/button/style/module/_buttons-group.scss
- src/component/modal/script/modal/modal-body.js
- src/component/modal/style/_module.scss
- src/component/tab/script/tab/tab-panel-direction.js
- src/component/tab/script/tab/tab-panel.js
- src/component/tab/script/tab/tab-selector.js
- src/component/tab/script/tab/tabs-group.js
- src/component/tab/style/_module.scss
- src/component/toggle/style/module/_toggle.scss
- src/core/script/api/internals.js
- src/core/script/api/scroll/scroll-locker.js
- src/core/script/api/utilities/motion/index.js
- src/core/script/api/utilities/motion/transition-selector.js
- src/core/script/collapse/collapse.js
- src/core/script/equisized/equisized.js
- src/core/script/equisized/equisizeds-group.js
- src/core/style/_module.scss
- src/core/style/collapse/_tool.scss
- src/core/style/display/module/_no-scroll.scss
- src/core/style/motion/_module.scss
> fix(core, tab, modal, button): injection js de styles en variables css [DS-2409][DS-2373]

- src/component/connect/.package.yml
- src/component/connect/example/index.ejs
- src/component/connect/example/sample/connect-default.ejs
- src/component/connect/example/sample/connect-plus.ejs
- src/component/connect/standalone/index.ejs
- src/component/connect/style/_module.scss
- src/component/connect/template/ejs/connect.ejs
- src/core/style/color/setting/_variable.scss
user-select: none; semble inutile
> feat(connect): ajout description et lien france connect [DS-2402]

- src/component/tab/style/_module.scss
Correction bug modal dans tab panel
> fix(tab): correction z-index des tab-panels [DS-2420]

- src/component/download/script/download/assess-file.js
- src/component/download/style/_scheme.scss
- src/component/download/style/module/_download.scss
- src/component/download/style/module/_group.scss
- src/component/download/template/ejs/downloads-group.ejs
> fix(download): titre groupe de liens en classe BEM [DS-246]

- CONTRIBUTING.md
- doc/legal/cgu.md
Ces amendements ont fait l'objet de discussions entre l'équipe DSFR du SIG et la direction juridique de la DINUM, qui les a validés.
> Amendements sur les CGU du DSFR

- module/color/mixin/_element.scss
- src/component/footer/example/index.ejs
- src/component/footer/example/sample/footer.ejs
- src/component/footer/style/_scheme.scss
- src/component/footer/style/module/_default.scss
- src/component/footer/template/ejs/brand.ejs
- src/component/footer/template/ejs/partners.ejs
- src/component/header/example/sample/header.ejs
- src/component/header/template/ejs/brand.ejs
- src/component/logo/template/ejs/logo.ejs
- src/core/style/action/module/_enlarge-link.scss
- src/core/style/action/tool/_hover.scss
- tool/example/decorator.ejs
correction du title du lien du logo du footer
agrandissement du hover du logo footer
Ajout de paramètres dans le template EJS de header et footer => brand.link { position, title, href)
> fix(footer, header): généralisation de l'attribut 'title' du lien retour/accueil du logo [DS-2682]

- package.json
@see https://github.com/GouvernementFR/dsfr/issues/388
> fix(global): Ajout du dossier "module"

- package.json
- src/component/tab/index.js
- src/component/tab/script/tab/tab-emission.js
- src/component/tab/script/tab/tab-keys.js
- src/component/tab/script/tab/tabs-group.js
- src/component/tab/script/tab/tabs-list.js
- src/component/tab/style/module/_shadow.scss
> fix(tab): écoute des événements de clavier déplacé sur la liste d'onglets [DS-2550]

- src/component/checkbox/style/_module.scss
- src/component/radio/style/module/_default.scss
- src/component/radio/style/module/_rich.scss
- src/component/radio/style/module/_sm.scss
Correction du placement de l'input affiché via voiceover
Changement de l'alignement à gauche des checkbox-group--sm et radio-group--sm
> fix(checkbox, radio): placement de l'input caché & alignement sm [DS-2941]

- src/component/pagination/example/sample/pagination.ejs
- src/component/pagination/style/_module.scss
- src/component/pagination/style/_setting.scss
Passage des boutons en taille sm
Ecart de 16px entre les boutons
Ajout de 'title' sur les boutons icones
> fix(pagination): ajustement taille et écart des boutons [DS-2931]

- module/color/variable/_decisions.scss
Rend les tokens de couleurs de fond :
- decorative
- background
- motif
Accessible pour toutes les couleurs d'artwork
- neutral
- primary
- accent
> feat(color): ajout de token de couleurs artwork

- src/core/script/api/api.js
- src/core/script/api/internals.js
- src/core/script/api/options/options.js
- src/core/script/api/utilities/search-params/index.js
- tool/example/example.ejs
Pour recuperer les parameres de query
> feat(api): ajoute une methode searchparams + config logs JS en prod [DS-2689]

- README.md
Fine tuning, ajout de licence et droit d'utilisation et corrections.
Aperçu du nouveau readme : https://github.com/GouvernementFR/dsfr/blob/fix/readme/README.md
> :sparkles: feat(readme): Mise à jour du readme [DS-3193]

- src/component/notice/.package.yml
- src/component/notice/example/index.ejs
Le nom du composant devient "Bandeau information importante"
> :bug: fix(notice): ajoute 'importante' au bandeau d'information importante [DS-3073]

- src/component/pagination/example/sample/pagination.ejs
- src/component/pagination/style/_module.scss
- src/component/pagination/style/_setting.scss
Harmonisation de l'espacement entre les boutons de pagination :
- L'espacement passe à 16px entre tous les boutons
- Les boutons passent en taille SM
> :sparkles: feat(pagination): évolution taille et écart des boutons [DS-2931]

- yarn.lock
> :arrow_up:  chore(dependencies): met a jour les dépendances Node [DS-3296]

- README.md
- src/core/.package.yml
- src/utility/.folder.yml
- src/utility/icons/.folder.yml
- src/utility/icons/icons-buildings/.package.yml
- src/utility/icons/icons-business/.package.yml
- src/utility/icons/icons-communication/.package.yml
- src/utility/icons/icons-design/.package.yml
- src/utility/icons/icons-development/.package.yml
- src/utility/icons/icons-device/.package.yml
- src/utility/icons/icons-document/.package.yml
- src/utility/icons/icons-editor/.package.yml
- src/utility/icons/icons-finance/.package.yml
- src/utility/icons/icons-health/.package.yml
- src/utility/icons/icons-logo/.package.yml
- src/utility/icons/icons-map/.package.yml
- src/utility/icons/icons-media/.package.yml
- src/utility/icons/icons-others/.package.yml
- src/utility/icons/icons-system/.package.yml
- src/utility/icons/icons-user/.package.yml
- src/utility/icons/icons-weather/.package.yml
- Mise à jour des liens vers les fondamentaux sur le site de documentation
> :pencil: doc(core): corrige les liens vers les pages de documentation des fondamentaux [DS-3298]

- src/component/form/style/module/_fieldset.scss
- src/component/input/input-email/i18n/fr.yml
- src/component/upload/i18n/fr.yml
- src/pattern/address/example/data/address.json.ejs
- src/pattern/address/i18n/fr.yml
- src/pattern/date/i18n/fr.yml
- src/pattern/name/i18n/fr.yml
- ajout d'indication et de description du format attendu
> ✨ feat(address): met a jour les message d'aide des champs de formulaire [DS-3295]

- src/analytics/script/integration/component/transcription/transcription-selector.js
- src/analytics/script/integration/component/translate/translate-selector.js
- src/component/accordion/script/accordion/accordion-selector.js
- src/component/accordion/script/accordion/accordions-group.js
- src/component/navigation/script/navigation/navigation-selector.js
- src/component/navigation/script/navigation/navigation.js
- src/component/sidemenu/script/sidemenu/sidemenu-list.js
- src/component/sidemenu/script/sidemenu/sidemenu-selector.js
- src/component/tab/script/tab/tab-panel.js
- src/component/tab/script/tab/tabs-group.js
- src/component/tab/style/_legacy.scss
- src/core/script/disclosure/disclosure.js
- src/core/script/disclosure/disclosures-group.js
- correction des marges sur les tabs imbriqués sur IE
- correction disclosure et disclosureGroup IE
- correction syntax error selecteur Collapse IE
> :bug: fix(tab): correction onglets imbriqués en legacy [DS-3313]

- tool/classes/changelog/changelog.ejs
- inclusion des caractères spéciaux html pour que les snippets soient affichés correctement
> 🐛 fix(changelog): correctif inclusion des html [DS-3317]

- README.md
- src/analytics/doc/analytics.md
- src/analytics/doc/analytics/collector/page.md
- src/analytics/doc/analytics/collector/site.md
- mise à jour du readme
- corrections diverses documentation analytics
> 📝 docs(analytics): correction doc analytics & readme [DS-3396]

- src/component/input/input-email/.package.yml
- src/component/input/input-email/i18n/fr.yml
- src/component/input/input-tel/.package.yml
- src/component/input/input-tel/i18n/fr.yml
- src/pattern/.folder.yml
- src/pattern/address/.package.yml
- src/pattern/address/i18n/fr.yml
- src/pattern/civility/.package.yml
- src/pattern/company/.package.yml
- src/pattern/company/i18n/fr.yml
- src/pattern/date/.package.yml
- src/pattern/date/i18n/fr.yml
- src/pattern/name/.package.yml
- src/pattern/name/i18n/fr.yml
- src/pattern/nationality/.package.yml
- src/pattern/nationality/i18n/fr.yml
- Mise à jour et harmonisation de la dénomination des blocs fonctionnels
> 🐛 fix(pattern): dénomination des blocs fonctionnels [DS-3393]

- src/analytics/example/spa/agnostic/index.ejs
- src/analytics/example/spa/angular/_index.ejs
- src/analytics/example/spa/react/index.ejs
- src/analytics/example/spa/vue/index.ejs
- src/component/form/template/ejs/message/messages-group.ejs
- remplace la valeur aria-live `assertive` par `polite`
> 🐛 fix(*): accessibilité aria-live [DS-3323]

- src/component/input/input-base/template/ejs/input.ejs
- conditionne l'ajout de la classe utile `fr-icon` à l'utilisation d'une string en paramètre `icon`
> 🐛 fix(password): bug icône [DS-3379]

- src/component/link/style/module/_download.scss
- retire le font-weight bold sur le lien de téléchargement
> 🐛 fix(link): corrige graisse lien de téléchargement [DS-3373]

- src/pattern/company/i18n/fr.yml
- src/pattern/name/example/data/name.json.ejs
- src/pattern/name/i18n/fr.yml
- Correction du langage dans la demande d'un représentant moral, suppression des pluriels optionnels
> 🐛 fix(company): retrait des pluriels [DS-3392]

- src/pattern/date/example/data/date.json.ejs
- src/pattern/date/example/sample/date-global-error.ejs
- src/pattern/date/example/sample/date-single-error.ejs
- mise en place de date cohérentes avec les erreurs affichées dans les exemples
> 🐛 fix(date): ajustement exemples [DS-3390]

- src/component/input/input-email/i18n/fr.yml
- src/component/upload/i18n/fr.yml
- src/pattern/address/i18n/fr.yml
- src/pattern/date/i18n/fr.yml
- src/pattern/name/i18n/fr.yml
- retrait de la capitalisation des mentions d'indication
> 🐛 fix(form): met a jour les libelles des indications [DS-3391]

- src/component/follow/.package.yml
- src/component/follow/example/data/newsletter-alert.json.ejs
- src/component/follow/example/index.ejs
- src/component/follow/example/sample/socials-newsletter-alert.ejs
- src/component/follow/template/ejs/newsletter.ejs
- Ajout de l'exemple de succès à l'abonnement à la lettre d'information
> 🐛 fix(follow): ajoute d'exemple [DS-3383]

- src/component/form/style/module/_fieldset.scss
- Ajuste la largeur des champs de code postal, année et nombre à des multiples de 8v
> 🐛 fix(input): ajustement champs particuliers [DS-3403]

- src/core/script/api/modules/register/instance.js
- Corrige la régression sur l'écoute des interactions avec le clavier dû à l'évolution de la structure de la constante KeyCodes, non répercutée dans KeyAction
> :bug: fix(core): correctif sur KeyAction [DS-3488]

- src/component/header/style/module/_nav.scss
- La navigation du header créée un scroll horizontal dans la page
- l'ajout d'un max-width prévient le problème
> :bug: fix(header): correctif régression scroll horizontal [DS-3514]

- src/component/card/style/_legacy.scss
- src/component/tile/style/_legacy.scss
- src/component/tile/style/module/_default.scss
- src/component/tile/style/module/_download.scss
- correctif sur les tuiles et card sur la version legacy pour éviter les bugs de dépassement de texte et placement des icones
> 🐛 fix(card, tile): correctif IE 11 [DS-3515]

- src/component/form/deprecated/style/_module.scss
- corrige le décalage du focus sur les boutons radio en version dépréciée
> fix(form): correctif focus des radios riches dépréciés [DS-3489]

- src/component/button/style/_module.scss
- src/component/button/style/_scheme.scss
- src/component/button/style/module/_account.scss
- src/component/button/style/module/_briefcase.scss
- src/component/button/style/module/_team.scss
- src/component/header/example/index.ejs
- src/component/header/example/sample/header.ejs
- src/component/header/style/_scheme.scss
- src/component/header/style/module/_links.scss
- src/component/header/template/ejs/tools.ejs
- src/component/translate/style/_module.scss
- ajoute des exemples avec un seul raccourcis dans la barre d'outils : Bouton de connexion seul, sélecteur de langue seul.
> Dans le cas où un quick access est unique, il ne doit pas être implémenté dans une liste.
> ✨ feat(header): mise à jour des exemples [DS-3544]

- src/component/footer/style/module/_bottom.scss
- corrige alignement des liens en bas du footer
> 🐛 fix(footer): correction alignement [DS-3381]

- src/component/quote/example/index.ejs
- src/component/quote/style/_module.scss
- src/component/quote/template/ejs/quote.ejs
- ajoute un exemple avec un seul detail dans `quote_source`
> 🐛 fix(quote): mise à jour des exemples [DS-2902]

- src/page/response/unexpected/i18n/fr.yml
- inverse les textes principal et de description du model de page
> 🐛 fix(page-unexpected): textes [DS-3398]

- src/component/stepper/style/_module.scss
- src/component/stepper/template/ejs/stepper.ejs
- inverse le stepper step et le title dans la pile html
> 🐛 fix(stepper): mise à jour de la structure [DS-3372]

- src/component/select/deprecated/example/sample/select.ejs
- src/component/select/example/sample/select.ejs
- src/component/select/style/_module.scss
- ajuste la taille et l'emplacement de la flèche
- corrige l'intitulé du placeholder
> 🐛 fix(select): correctifs flèche et intitulé [DS-3534, DS-3536]

- src/core/example/reset/index.ejs
- src/core/example/reset/sample/dl.ejs
- src/core/style/typography/module/_list.scss
- Ajout d'un exemple de liste de description dans core/reset
> ✨ feat(core): ajout du style par défaut des listes de description dl dt dd [DS-1888]

- src/component/consent/example/sample/modal/body.ejs
- src/component/consent/style/module/_services.scss
- étend le lien "voir plus de detail" pour être entièrement cliquable
> 🐛 fix(consent): correction lien [DS-3490]

- src/pattern/name/example/data/name.json.ejs
- src/pattern/name/example/js/add-firstname.js
- Dans le pattern de nom prénom, les boutons d'ajout et de suppression de prénom passent en secondaire à la place de tertiaire
> 🐛 fix(name): bouton ajout et suppression en secondaire [DS-3584]

- yarn.lock
> ⬆️ chore(dependencies): met a jour les dépendances Node [DS-3632]

- src/core/script/api/modules/register/instance.js
- correction de la fonction dispose sur Instance pour enlever les écouteurs sur la modification du hash de l'url
> 🐛  fix(core): correctif garbage collection hash [DS-3633]

- CONTRIBUTING.md
- ajout du formattage shell pour les snippets de code
- correction de fautes d'ortographe
> 📝 doc(contributing): typos et formattage de la doc de contribution

- src/component/display/deprecated/example/index.ejs
- src/component/display/example/index.ejs
- src/component/download/example/index.ejs
- src/component/highlight/example/index.ejs
- src/component/pagination/example/index.ejs
- src/component/tab/example/index.ejs
- src/component/tile/example/index.ejs
> 🐛 fix(examples): met a jour les pages d'exemple

- src/core/script/api/utilities/dom/classes.js
- correction d'une erreur js sur IE lors de la récupération du classname dans l'instance
> 🐛 fix(core): classname IE [DS-3641]

- src/core/script/api/utilities/dom/classes.js
- régression sur la fonction getClassname du core
> 🐛 fix(core): erreur js classname

- src/component/header/style/module/_links.scss
- corrige la taille des boutons d'accès rapide dans le menu mobile
> 🐛  fix(header): espacement des liens d'accès rapide en mobile [DS-3683]

- yarn.lock
- monté de version des dépendances à follow-redirects et semver
> ⬆️ chore(dependencies): met a jour les dépendances Node

- src/component/range/script/range/range-input.js
- corrige un bug js sur l'écouteur d'événement
> 🐛 fix(range): correctif dispose input [DS-3748]

- src/component/toggle/style/module/_default.scss
- Corrige le retour à la ligne sur le label "activé/désactivé" #907
> 🐛 fix(toggle): retour à la ligne statut activé/désactivé [DS-3791]

- src/core/index.ejs
- tool/example/heading.ejs
- affiche la version du DSFR en haut des pages d'exemple
> ✨ feat(build): ajoute le numéro de version dans les pages d'exemple [DS-1460]

- module/legacy/mixin/_legacy.scss
- src/component/accordion/style/_module.scss
- src/component/button/style/module/_default.scss
- src/component/notice/style/_legacy.scss
- src/component/table/deprecated/style/_legacy.scss
- src/component/table/deprecated/style/module/_variants.scss
- src/component/table/example/data/data-lorem.json.ejs
- src/component/table/example/index.ejs
- src/component/table/i18n/fr.yml
- src/component/table/style/_legacy.scss
- src/component/table/style/module/_default.scss
- src/component/table/style/module/_variants.scss
- src/component/table/template/ejs/wrapper.ejs
- src/component/toggle/style/module/_default.scss
- ajout d'une version de tableau sans scroll, avec réduction automatique des cellules
> ✨ feat(table): ajoute le tableau non scrollable [DS-3742]

- src/component/toggle/example/sample/toggle-default.ejs
- src/component/toggle/style/_scheme.scss
- src/component/toggle/style/module/_default.scss
- src/component/toggle/style/module/_group.scss
- src/component/toggle/template/ejs/toggle.ejs
- Retrait des marges avant et après le composant
- ajoute la bordure en état d'erreur/succès
> 🐛 fix(toggle): ajoute les messages erreur et valide sur interrupteur simple

- src/component/breadcrumb/style/_module.scss
- src/component/card/style/module/_content.scss
- src/component/connect/style/module/_group.scss
- src/component/consent/style/module/_services.scss
- src/component/form/deprecated/style/_module.scss
- src/component/modal/style/_module.scss
- src/component/radio/deprecated/style/_module.scss
- src/component/select/style/_module.scss
- src/component/summary/style/_module.scss
- src/core/style/display/tool/_hr.scss
- corrections diverses sur le mode contrasté
> 🐛 fix(preference): correctifs mode contrasté et reduce motion [DS-3773]

- src/component/table/deprecated/example/index.ejs
- src/component/table/deprecated/style/_legacy.scss
- src/component/table/deprecated/style/_scheme.scss
- src/component/table/deprecated/style/module/_default.scss
- src/component/table/deprecated/style/module/_variants.scss
- src/component/table/example/data/data-complex-tbody.json.ejs
- src/component/table/index.js
- src/component/table/main.js
- src/component/table/script/table/table-caption.js
- src/component/table/script/table/table-selector.js
- src/component/table/script/table/table-wrapper.js
- src/component/table/style/_legacy.scss
- src/component/table/style/_scheme.scss
- src/component/table/style/module/_default.scss
- src/component/table/style/module/_variants.scss
- src/core/style/collapse/_tool.scss
- déplace bordures des tableaux déprécies sur les thead et tbody
- retire les selecteurs css :has
> 🐛 fix(table): corrige regressions sur les tableaux déprécies [DS-3804]

- src/core/script/api/modules/register/instance.js
- Correction du retour du getter instance.node qui engendrait une boucle infinie
> 🐛 fix(core): Bug de récursivité infinie sur le getter node [DS-3841]

- src/analytics/example/spa/angular/_index.ejs
- src/analytics/example/spa/react/index.ejs
- src/analytics/example/spa/vue/index.ejs
- correction des collectes d'actions des pages d'exemples react et vue ( fix #990 )
> 🐛 fix(analytics): lancement dsfr start dans les pages SPA  [DS-3855]

- src/component/pagination/example/sample/pagination.ejs
- remplace le lien par un span sur les points de suspension
> ✨ feat(pagination):  retire lien sur les points de suspension

- src/component/notice/style/_module.scss
- changement de l'icône par défaut du bandeau d'alerte météo rouge
> ✨ feat(notice): icone alerte météo rouge [DS-3838]

- src/component/toggle/style/module/_group.scss
- corrige les espacements des groupes d'interrupteurs dépréciés
> 🐛 fix(toggle): correction groupe d'interrupteurs dépréciés [DS-3835]

- src/component/header/style/module/_brand.scss
- src/component/sidemenu/style/module/_action.scss
- src/component/sidemenu/style/module/_variants.scss
- correction du focus croppé sur la navigation latérale #980 
- correction du focus croppé sur le header en mobile
> 🐛 feat(sidemenu): correction focus sidemenu sticky [DS-3842]

- src/component/range/style/_module.scss
- Amélioration du design du curseur en mode couleurs forcées
> 🐛 fix(range): amélioration du rendu en mode contrasté [DS-3808]

- src/component/header/script/header/header-links.js
- permet la duplication des attributs aria dans le menu mobile des accès rapides
> :bug: fix(header): duplication aria-describedby & labelledby [DS-3827]

- src/component/tooltip/script/tooltip/tooltip-selector.js
- src/component/tooltip/script/tooltip/tooltip.js
- src/component/tooltip/style/_module.scss
- src/core/script/placement/placement.js
- src/core/style/placement/_module.scss
- Correction du placement du tooltip dans un élément possédant un filter (modal, header)
- Gestion du placement en position absolute plutot que fixed
> 🐛 fix(core, tooltip): positionnement du tooltip dans header & modale [DS-3733]

- src/dsfr/component/tab/script/tab/tabs-list.js
- Correction de l'ombre au scroll en direction RTL
> 🐛 fix(tab): correction de l'ombre au scroll en RTL

- src/dsfr/component/input/input-base/style/_module.scss
- src/dsfr/component/input/input-base/style/_scheme.scss
- corrige le focus du date-picker
> 🐛 fix(input): focus date-picker [DSFR-54]

- src/dsfr/component/button/template/stories/button-arg-types.js
- src/dsfr/component/button/template/stories/button.js
- src/dsfr/component/header/script/header/header-modal.js
- src/dsfr/component/header/script/header/header-selector.js
- src/dsfr/component/modal/example/index.ejs
- src/dsfr/component/modal/example/sample/modal-default.ejs
- src/dsfr/component/modal/script/modal/modal-body.js
- src/dsfr/component/modal/script/modal/modal.js
- src/dsfr/component/modal/template/ejs/button.ejs
- src/dsfr/core/script/api/modules/register/focus-manager.js
- src/dsfr/core/script/api/modules/register/instance.js
- src/dsfr/core/script/disclosure/disclosure-type.js
- src/dsfr/core/script/disclosure/disclosure.js
- src/dsfr/core/script/disclosure/disclosures-group.js
- **focusManager** gère le retour du focus en cas d'absence d'un bouton primaire.
- correction du bug focus bloqué sur les menu du header
> 🐛 fix(modal): bouton non requis + correctif [DSFR-17, DSFR-26]

- src/dsfr/component/tag/style/_scheme.scss
- Correction du hover des tags sélectionnables désactivés
> 🐛 fix(tag): bug hover tags sélectionnables désactivés

- package.json
Ajouts des fichiers à l'export :
- CONTRIBUTING.md,
- CHANGELOG.md",
- LICENSE.md,
- README.md,
- publiccode.yml
> ✨ feat(package.json): ajout des fichiers markdown et publiccode

- src/dsfr/component/notice/template/stories/notice-arg-types.js
- Ajout du type de bandeau d’alerte "weather-red" dans storybook
> 🐛 fix(storybook): ajout bandeau alerte météo rouge dans le storybook

- src/dsfr/analytics/doc/analytics/collector/user.md
- src/dsfr/analytics/doc/analytics/installation/configuration.md
- corrige des liens en 404 #1136
> 📝 docs(analytics): links fix [DSFR-99]

- src/dsfr/component/modal/.package.yml
- src/dsfr/component/modal/example/index.ejs
- src/dsfr/component/modal/example/sample/body/table.ejs
- src/dsfr/component/modal/script/modal/modal.js
- lorsqu'une tooltip est ouverte dans une modale la touche `escape` ferme uniquement la tooltip
> ✨ feat(modal, tooltip): ajoute une condition a la fermeture de la modale

- src/dsfr/component/link/deprecated/template/ejs/link.ejs
- src/dsfr/component/link/example/index.ejs
- Corrige une régression sur l'exemple de lien externe
> 🐛 fix: correction exemple lien externe [DSFR-112]

- dsfr-sb/.storybook/dsfr-theme.js
- Correction du thème sur les iframes storybook insérées dans la doc.
> 🐛 fix(storybook): applique la gestion du thème dsfr sur les iframes storybook

- dsfr-sb/.storybook/preview.css
- src/dsfr/component/display/template/stories/display.stories.js
- src/dsfr/component/modal/script/modal/focus-trap.js
- src/dsfr/component/modal/script/modal/modal-body.js
- src/dsfr/component/modal/style/_module.scss
- Lorsque la page est insérée dans une iframe plus petite que le viewport les marges en haut et en bas de la modale prennent 10% de la page et non 10% de l'iframe
> 🐛 fix(modal): marges de la modale en pourcentage

- src/dsfr/component/button/_part/doc/code/index.md
- src/dsfr/component/display/_part/doc/code/index.md
- src/dsfr/component/footer/_part/doc/code/index.md
- src/dsfr/component/link/_part/doc/code/index.md
- src/dsfr/component/tooltip/_part/doc/code/index.md
- src/dsfr/layout/pattern/forms/_part/doc/index.md
- corrections documentation button, link, footer, display, tooltip
#1269
> 📝 docs: correction mineures documentation
