GouvernementFR/dsfr

- examples/example.ejs
- src/checkboxes/example/samples/checkbox.ejs
- src/checkboxes/styles/_module.scss
- src/radios/styles/_legacy.scss
- src/radios/styles/_module.scss
- src/radios/styles/modules/_radios-rich.scss
Problèmes : 
Les labels passent à la ligne du bouton si plus grand que l'écran.
Les radios riches ne s'étendent pas verticalement
Solution apportée : 
Position absolute sur les inputs
Margin-left sur le label
Les radios riches ne s'étendent pas que sur IE maintenant (pour conserver l'alignement vertical et éviter un breaking change)
Evolutions : 
Les radios et checkboxes en taille SM sont maintenant plus espacés du label (comme sur la lib UI)
Ajout du css du package legacy dans les dépendances des pages d'exemples
L'input reste maintenant aligné en haut si le label passe sur plusieurs lignes
> fix(checkboxes, radios): input en position absolue [DS-1924]

- src/component/input/style/_scheme.scss
On retire le box shadow particulier sur les textarea. 
=> L'icone native pour agrandir le textarea passe par dessus le box shadow
> fix(input): fr-input--error sur un textarea le passe en rouge [DS-1577]

- src/core/style/reset/module/_input.scss
Reset du border et border-radius pour surcharger le comportement par défaut d'IOS sur les input[type=submit] notamment.
> fix(core): reset bordure des inputs [DS-1983]

- .gitignore
- package-lock.json : Si vous utilisez uniquement yarn, le fichier ne devrait pas être généré ?
- yarn.lock: il ne devrait pas être ignoré
Concernant le reste, je trouve plus pertinent que ces fichiers (configurations de l'IDE propre au développeur) soient dans un gitignore global (https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files#configuring-ignored-files-for-all-repositories-on-your-computer).
> refactor: modification du gitignore

- src/core/script/api/options/options.js
@lab9fr j'ai défini une valeur par défaut pour les settings pour ne pas être obligé de passer l'objet `window.dsfr` à l'instanciation de l'api.
NB : 
si on instancie pas l'objet dsfr on a une erreur au chargement de la lib :
> Fix: définition d'une valeur par défaut de l'objet de configuration window.dsfr [DS-2085]

- src/component/content/example/sample/media-img.ejs
- src/component/form/template/ejs/fieldset.ejs
- src/component/input/example/index.ejs
- src/component/input/example/sample/input-button.ejs
- src/component/radio/example/sample/radio-rich.ejs
- src/component/radio/example/sample/radio.ejs
- src/component/select/example/index.ejs
- src/component/select/example/sample/select.ejs
- src/component/toggle/template/ejs/toggle.ejs
- src/component/upload/template/ejs/upload.ejs
ajout de fichier | manque le message d’erreur |   | OK |  
-- | -- | -- | -- | --
form | sur l’exemple ‘Ensemble de champs de saisie désactivés’<fieldset disabled=”disabled” … | passer en disabled uniquement<fieldset disabled … | OK |  
Content | valeur alt à modifier | 1<img src="/img/image.jpg" class="fr-responsive-img" alt="[À MODIFIER \| vide ou texte alternatif de l’image]" /> 2 vide ou texte alternatif de l’imageL’alternative de l’image (attribut alt) doit toujours être présent, sa valeur peut-être vide ou non selon votre contexteCe sera plus vrai et plus correctEn attendant -  si pas possible rapdiment de modifier la function alt - mettre à vide | OK |  
Select | exemple disabled n’est pas “wrappé” par un bloc disabledfr-input-group--disabledle label n’est pas grisé du coup…. |   | …
> fix: correctifs ejs form [DS-1854]

- src/legacy.js
- src/legacy/legacy.js
- src/legacy/main.js
Quickfix pour corriger les erreurs JS sur les navigateurs modernes, en attendant de corriger le build pour ignorer le package '/legacy' au build du script 'dsfr.module.js'
> fix(legacy): retire les polyfills legacy du script module [DS-2304]

- package.json
- src/component/input/style/_tool.scss
- tool/build/styles.js
- yarn.lock
De même, dans la foulée de #278, il semblerait que cette dépendance soit historiquement présente mais plus utilisée
> chore: suppression de node-sass-magic-importer

- src/component/download/script/download/assess-file.js
- src/component/download/script/download/download-selector.js
La fonctionnalité de récupération de poids du fichier du JS asses-file est désactivé sur IE
> fix(download): correction erreur js legacy [DS-2540]

- package.json
- src/component/card/style/module/_horizontal.scss
- src/component/content/style/_tool.scss
- src/component/link/style/tool/_icon.scss
- src/component/link/style/tool/_size.scss
- src/component/logo/style/_module.scss
- src/component/logo/style/_tool.scss
- src/component/radio/style/_tool.scss
- src/core/style/function/_string.scss
- src/core/style/function/_unit.scss
- src/core/style/media/_setting.scss
- src/core/style/media/_tool.scss
- src/core/style/spacing/function/_space.scss
- src/core/style/spacing/tool/_margin.scss
- tool/build/styles.js
- yarn.lock
Cette *pull-request* sert de base de travail pour migrer le DSFR vers Dart Sass (cf. #254).
> chore(deps): migration vers dart sass

- src/component/stepper/style/_module.scss
- src/component/stepper/style/_tool.scss
utiliser fr-unhidden sur le detail pour overrider le comportement
> fix(stepper): cache le détail de la dernière étape en css [DS-2446]

- src/component/toggle/script/toggle/toggle-input.js
initialise correctement l'état checked du composant même si l'attribut html 'checked' est absent
Aujourd'hui le composant ne permet pas d'initialiser le composant en état checked avec [vite](https://vitejs.dev/guide/)+[svelte](https://svelte.dev/).
Le comportement erroné est visible dans le repo [demo-vite-dsfr](https://github.com/emillumine/demo-vite-dsfr). Il s'agit du projet d'exemple obtenu avec `npm init vite` dans lequel on a ajouté le dsfr et un composant Toggle.svelte.
Pour lancer le projet : 
```
npm install
npm run dev
```
Le dsfr a été installé dans public/dsfr.
Le composant toggle possède l'attribut html "checked" (src/lib/Toggle.svelte) mais il n'est pas activé sur la page.
> fix(toggle): rend le composant compatible avec vite+svelte

- src/component/modal/script/modal/focus-trap.js
à l'ouverture de la modale, le focus est automatiquement déplacé sur le premier des éléments interactifs de la modale. 
Ce comportement pose problème lorsque le focus est déjà sur un des éléments contenus dans la modale.
Ajout d'une condition qui vérifie que le focus n'est pas déjà sur un des éléments interactifs de la modale avant de déplacer le focus.
> :bug: fix(modal): correctif prise de focus au focus-trap [DS-3211]

- src/component/password/script/password/password-input.js
Lorsque le navigateur fait l'autocompletion du champ password, il lance un évènement qui n'est pas forcément un évènement de clavier et provoque une erreur indiquant que la fonction getModifierState n'existe pas.
> :bug: fix(password): correctif erreur getModifierState [DS-2940]

- src/core/style/media/module/_responsive.scss
Dans le cas d'une video le placeholder est en display block
Retrait de la propriété non désirée
> :bug: fix(consent): consent placeholder video mal centré [DS-3026]

- src/component/footer/example/sample/footer.ejs
Nouveau texte : ”Sauf mention explicite de propriété intellectuelle détenue par des tiers, les contenus de ce site sont proposés sous”
> :sparkles: feat(footer): évolution des mentions légales [DS-3140]

- src/component/transcription/style/_module.scss
à l'ouverture de la modale de la transcription, le déplacement des éléments en position fixed change la taille du bouton de la transcription à sa taille minimum. 
La largeur étendue à 100% permet de la conserver constante.
> 🐛 fix(transcription): corrige largeur du bouton a l'ouverture de la modale [DS-3070]

- CONTRIBUTING.md
- tool/build/scripts.js
- tool/build/styles.js
- tool/utilities/file.js
Sur windows il n'est pas possible de recompiler le projet avec yarn build
Correction des path dans les tools (windows utilise "\" et linux et mac "/")
> :bug: fix(build): changement des path pour compiler sur windows [DS-2992]

- .github/ISSUE_TEMPLATE/1-bug.md
- .github/ISSUE_TEMPLATE/2-suggestion.md
- .github/ISSUE_TEMPLATE/3-doc.md
- .github/ISSUE_TEMPLATE/config.yml
Création de template d'issue Github pour indiquer les informations demandées lors d'un report de 
- bug
- évolution
- documentation
> ✨ feat(github): ajout de templates d'issue github [DS-3201]

- CONTRIBUTING.md
- tool/build/scripts.js
- tool/build/styles.js
- tool/utilities/file.js
Sur windows il n'est pas possible de recompiler le projet avec yarn build
Correction des path dans les tools (windows utilise "" et linux et mac "/")
> 🐛 fix(build): changement des path pour compiler sur windows [DS-2992]

- src/component/input/input-base/style/_module.scss
- src/component/input/input-base/style/_scheme.scss
Sur firefox depuis la version 109, le date picker est doublé.
- Afficher uniquement le datepicker natif sur firefox 109+
> :bug: fix(input): correctif input date-picker sur firefox 109+ [DS-2547]

- src/component/input/input-base/style/_module.scss
- src/component/input/input-base/style/_scheme.scss
- src/component/input/input-base/style/_tool.scss
- src/component/password/script/password/password-input.js
- src/component/password/script/password/password-toggle.js
- src/component/password/style/_module.scss
- src/component/password/template/ejs/password.ejs
- src/page/account/login/example/data/login.json.ejs
- src/page/account/register/example/data/login.json.ejs
- Correction erreur js sur le champ password au clic sur le trousseau (safari)
- Retrait icone native capslock safari
- Ajout attribut `autocapitalize='off'` sur les champs password et email pour désactiver la majuscule au début (mobile)
- Ajout attribut `autocorrect` sur les champs password et email pour désactiver la correction orthographique
> :bug: fix(password, account): correction capslock safari [DS-2942]

- module/selector/mixin/_theme.scss
- src/component/button/style/module/_group.scss
La propriété CSS :where est encore trop récente (chrome 88).
-> retrait de cette propriété
> 🐛 fix(button, theme): retrait propriété css :where [DS-2759]

- src/core/style/display/module/_hr.scss
Il y a un `-` en trop.
Voir https://www.w3.org/TR/css-flexbox-1/#flex-wrap-property
partial-fix de #593
> 🐛 fix(core): La valeur no-wrap n’existe pas dans la spécification CSS

- src/component/follow/style/_module.scss
- src/component/input/input-base/example/index.ejs
- src/component/input/input-base/example/sample/input-action.ejs
- src/component/input/input-base/i18n/fr.yml
- src/component/input/input-base/style/_module.scss
- src/component/input/input-base/style/_scheme.scss
- src/component/input/input-base/template/ejs/input.ejs
- src/pattern/name/example/data/js/add-firstname.js
- src/pattern/name/example/data/js/remove-firstname.js
- src/pattern/name/i18n/fr.yml
Dans le modèle de de bloc nom/prénom, un bouton permet d'ajouter des champs de saisie pour les prénoms secondaires -> ajout d'un bouton permettant de supprimer ces champs ajoutés
> :sparkles: feat(name): ajout bouton de suppression de prénom [DS-2974]

- src/component/tab/index.js
- src/component/tab/script/tab/tab-emission.js
- src/component/tab/script/tab/tab-keys.js
- src/component/tab/script/tab/tabs-group.js
- src/component/tab/script/tab/tabs-list.js
- src/component/tab/style/module/_shadow.scss
L'écoute des événements de clavier se faisant sur le composant, il est impossible d'interagir avec des éléments de formulaire dans le contenu de l'onglet -> l'écoute est déplacée au niveau de la liste des onglets, ce qui en exclut le contenu
> :bug: fix(tab): écoute des événements de clavier déplacé sur la liste d'onglets [DS-2550]

- module/color/mixin/_data-uri-svg.scss
- src/component/checkbox/deprecated/style/_module.scss
- src/component/checkbox/index.scss
- src/component/checkbox/legacy.scss
- src/component/checkbox/style/_legacy.scss
- src/component/checkbox/style/_module.scss
- src/component/checkbox/style/_scheme.scss
- src/component/checkbox/style/_tool.scss
- src/component/form/style/_scheme.scss
- src/component/radio/deprecated/style/_module.scss
- src/component/radio/style/_tool.scss
- src/component/radio/style/module/_default.scss
- src/component/radio/style/module/_rich.scss
- src/component/radio/style/module/_sm.scss
- src/component/radio/style/scheme/_default.scss
- src/component/radio/style/scheme/_rich.scss
- src/component/radio/style/scheme/_sm.scss
- src/component/toggle/example/index.ejs
- src/component/toggle/example/sample/toggle-group.ejs
- src/component/toggle/style/_legacy.scss
- src/component/toggle/style/_scheme.scss
- src/component/toggle/style/_setting.scss
- src/component/toggle/style/module/_default.scss
- src/component/toggle/style/module/_group.scss
- src/component/toggle/style/module/_variants.scss
- src/component/toggle/template/ejs/toggle.ejs
- src/core/style/action/setting/_elements.scss
Uniformisation des champs à cocher toggle/radio/checkbox
toggle:
- Ajout des variants toggle error/valid
- Retrait du css sur input `appearance:none` 
- bordure en background svg
- le toggle est maintenant placé dans un fieldset
radio:
- Le contour devient bleu
- retrait du fond blanc du radio bouton (transparence)
- input déssiné en background image
radio-rich: 
- L'outline au focus englobe tout le radio-riche, plus l'input
checkbox:
- Le contour devient bleu
- correction changement d'état au mouse-down (:active), maintenant au mouse up
Form: 
- les hint-text des champs désactivés passent en couleur `--text-disabled-grey`
> :recycle: refactor(radio,checkbox,toggle): passage input en bleu et refactorisation [DS-2897,DS-2899, DS-2182, DS-2778, DS-3048]

- src/component/header/style/module/_nav.scss
- src/component/navigation/example/sample/navigation.ejs
- src/component/navigation/style/module/_default.scss
- src/component/navigation/style/module/_mega-menu.scss
- src/component/navigation/style/scheme/_mega-menu.scss
- src/component/sidemenu/style/module/_list.scss
- L'outline de focus est maintenant entièrement visible sur les liens des sous menu en mobile
- Ajustement de l'alignement du bouton fermé en desktop
- Retrait du mega-menu__leader vide dans les examples
> :bug: fix(header, navigation): focus des nav-items mobile & ajustements [DS-3216]

- src/core/style/_outdated.scss
- src/core/style/action/tool/_link.scss
- La fonction css max(), mise en place pour corriger le bug d'affichage d'un soulignement d'une épaisseur inférieure à 1px, est supportée à partir de la version 78 de firefox, ce qui est insuffisant.
- Le précédent bug est maintenant corrigé avec un léger épaississement du trait sur firefox (0.25px)
> :bug: fix(core): corrige liens pour retro-compat sur firefox [DS-3288]

- module/color/variable/_box-shadows.scss
- src/component/display/example/sample/body.ejs
- src/component/form/deprecated/style/_module.scss
- src/component/form/style/module/_fieldset.scss
- src/component/radio/deprecated/example/sample/radio-rich.ejs
- src/component/radio/deprecated/style/_module.scss
- src/component/radio/deprecated/style/_scheme.scss
- src/component/radio/example/index.ejs
- src/component/radio/example/sample/radios-rich.ejs
- src/component/radio/legacy.scss
- src/component/radio/main.scss
- src/component/radio/style/module/_default.scss
- src/component/radio/style/module/_rich.scss
- src/component/radio/style/scheme/_rich.scss
- src/component/radio/template/ejs/radio.ejs
- src/core/style/action/setting/_elements.scss
- src/core/style/artwork/_scheme.scss
Les radios riches doivent utiliser des pictogrammes et non des images.
Retrait des images
Ajout de pictograme
Le snippet :
```html
<div class="fr-radio-group fr-radio-rich">
<input value="1" type="radio" id="radio-rich-1" name="radio-rich">
<label class="fr-label" for="radio-rich-1">
Libellé bouton radio
</label>
<div class="fr-radio-rich__img">
</div>
</div>
```
DEVIENT : 
```html
<div class="fr-radio-group fr-radio-rich">
<input value="1" type="radio" id="radio-rich-1" name="radio-rich">
<label class="fr-label" for="radio-rich-1">
Libellé bouton radio
</label>
<div class="fr-radio-rich__pictogram">
<svg aria-hidden="true" class="fr-artwork" viewBox="0 0 80 80" width="80px" height="80px">
<use class="fr-artwork-decorative" href="../../../dist/artwork/pictograms/buildings/city-hall.svg#art …
```
> ✨ feat(radio): radio rich sans images & pictogram à la place d'img [DS-1315]

- src/component/tab/style/_legacy.scss
- src/component/tab/style/module/_default.scss
- src/core/style/typography/_legacy.scss
- Corrige la taille de l'icône
- Corrige l'alignement du contenu du tab_panel
- Ajustement du padding de la tab__list
- Retire les margin-top des headings (h1 -> h6)
> :bug: fix(tab, core): correctif tab legacy & margin top des headings [DS-3281]

- src/page/account/login/example/data/login.json.ejs
- src/page/account/recover/example/data/recover.json.ejs
- src/page/account/register/example/2-steps/2a-login/index.ejs
- src/page/account/register/example/data/address.json.ejs
- src/page/account/register/example/data/identity.json.ejs
- src/page/account/register/example/data/login.json.ejs
- src/page/account/template/ejs/blocks/colored.ejs
- src/page/account/template/ejs/blocks/heading.ejs
- src/page/account/template/ejs/segments/button.ejs
- src/page/account/template/ejs/segments/connect.ejs
- src/page/account/template/ejs/segments/heading.ejs
- src/page/account/template/ejs/segments/stepper.ejs
- Mise en place d'une hiérarchie sans saut de niveau de titre, plus cohérente
- Correctif typo sur la classe `fr-grid-row--gutters`
> :bug: fix(account): met a jour la hiérarchie html des modèles de page [DS-3289,  DS-3290]

- src/component/share/example/sample/share-default.ejs
- Gestion de la Promise retournée par `navigator.clipboard.writeText()`
> :bug: fix(share): correction copie url dans presse papier [DS-3309]

- src/component/search/style/_module.scss
- src/core/style/action/module/_input.scss
- En utilisant des librairies tierces (telles que normalize.css), le champ de recherche reprend son aspect natif arrondi en mobile IOS. 
- Spécificité renforcée sur le sélecteur afin de conserver le `appearance: none`
> :bug: fix(search): apparence du champ de recherche iOS

- src/component/link/style/tool/_build.scss
Retrait du z-index: 1 qui pose problème dans une modale avec footer.
> :bug: fix(link, button, tag, badge): retrait du z-index [DS-3285]

- tool/example/style.ejs
- l'attribut file n'est pas un attribut possible pour les éléments <link>
> :bug: fix(example): retire les attributs file des <link> [DS-3307]

- src/component/input/input-base/style/_module.scss
- src/component/input/input-base/style/_scheme.scss
- src/component/select/style/_module.scss
- src/component/select/style/_scheme.scss
Actuellement la bordure gauche montrant l'état d'erreur/succès/info n'est appliqué que dans le cas d'un groupe de champ en erreur via les modificateur .fr-fieldset--error, .fr-fieldset--valid, .fr-fieldset--info
Afin d'être ISO avec l'UI nous rajoutons cet élément visuel sur : 
- les champs seuls (.fr-input-group) : 
- `.fr-input-group--error`
- `.fr-input-group--valid`
- `.fr-input-group--info`
- les selects (.fr-select-group)
- `.fr-select-group--error`
- `.fr-select-group--valid`
- `.fr-select-group--info`
> :sparkles: feat(select, input): ajout de la bordure en état erreur / succés / info [DS-3308]

- src/component/search/style/_module.scss
Sur ios le champ dépasse de 1px par rapport au bouton.
-> Correction du max-height
> :bug: fix(search): hauteur du champ trop grande de 1px sur ios [DS-3312]

- src/component/header/script/header/header-links.js
- L'ensemble des id présents dans les accès rapides du header doivent être suffixés par -mobile à la duplication
> :bug: fix(header): duplication des id généralisée pour les quick access [DS-3306]

- src/analytics/script/analytics/utils/hierarchy/member.js
- l'analyse de hiérarchie ignorait les headings présents dans un composant. Ce correctif règle le problème.
> :bug: fix(analytics): correctif hiérarchie [DS-3394]

- src/core/script/action/toggle/toggle.js
- Dans la class Toggle, le proxy appelle la fonction toggle qui a été remplacée par la fonction générique handleClick : 
- Ce correctif restaure la fonction toggle et implémente son appel dans handleClick
> 🐛 fix(core): correctif bug proxy Toggle [DS-3351]

- package.json
- Monte la version minimale de NodeJS en 18.16.1
> ⬆️ chore(*): montée de version NodeJS 18 [DS-3319]

- src/core/style/spacing/tool/_margin.scss
- ajoute une condition pour éviter le padding négatif actuellement présent dans les classes utiles
> 🐛 fix(core): correctif padding négatif [DS-3322]

- src/page/account/login/example/data/login.json.ejs
- src/page/account/login/i18n/fr.yml
- src/page/account/register/example/data/address.json.ejs
- src/page/account/register/example/data/identity.json.ejs
- src/page/account/register/example/data/login.json.ejs
-  La mention de "champs obligatoires" doit être mise dans un élément `<p>` sur les pages de connexion et création de compte
> 🐛 fix(account): accessibilité champs obligatoires [DS-3320]

- src/page/response/template/ejs/response.ejs
- ajoute une condition sur l'ajout du wrapper `.fr-btns-group` dans la template `ejs`
> 🐛 fix(unexpected): corrige groupe de bouton vide [DS-3324]

- src/component/tile/template/ejs/content.ejs
- src/pattern/company/example/data/siret.json.ejs
- corrige l'accessibilité du lien en `target="_blank"` par l'ajout d'un attribut `title`  :  "Annuaire des entreprises – nouvelle fenêtre"
> 🐛 feat(company): accessibilité lien externe [DS-3326]

- src/component/pagination/example/sample/pagination.ejs
- Corrige la régression qui a supprimé les liens des éléments de pagination
> :bug: fix(pagination): correctif régression href des exemples [DS-3380]

- src/component/consent/style/_scheme.scss
- src/component/consent/style/_setting.scss
- src/component/consent/style/module/_services.scss
- Corrige description d'une finalité de 3v à 2v en margin-bottom
- Homogénéité avec accordion, nav et sidemenu sur le bouton de la modale de consentement “voir plus de détails” :
- enlever le soulignement
- mettre en bleu le lien “voir plus de détail”
> 🐛 fix(consent): correctif espacement et couleur [DS-3370, DS-3369]

- src/component/footer/style/module/_bottom.scss
- retrait de CSS résiduel de précédentes versions dans le footer-bottom__list
> :bug: fix(footer): retrait de CSS obsolète [DS-3404]

- src/pattern/name/example/index.ejs
- src/pattern/name/example/js/add-firstname.js
- src/pattern/name/example/js/remove-firstname.js
- src/pattern/name/example/js/toggle-disabled.js
Ajoute dans la page d’exemple le déplacement du focus : 
- au click sur la checkbox de désactivation pour activer, le premier champ ou bouton prend le focus
- au click sur l’ajout d’un prénom, le champs ajouté prend le focus
- au click sur la suppression, le champ ou bouton suivant prend le focus
> 🐛 fix(name): a11y - gestion du focus [DS-3325]

- src/component/password/style/_module.scss
- Sur edge une icône oeil apparaît au focus d'un champ de type "password"
- Retrait de l'icone native
> :bug: fix(password): retrait du bouton natif sur edge [DS-3378]

- src/pattern/civility/example/data/honorific-radio.json.ejs
- Corrige la taille des boutons radio du titre d'appel en sm au lieu de md
> 🐛 fix(civility): correctif taille des boutons radio [DS-3389]

- src/component/accordion/style/_module.scss
- src/component/header/style/module/_links.scss
- src/component/header/style/module/_nav.scss
- src/component/navigation/style/module/_default.scss
- src/component/navigation/style/module/_mega-menu.scss
- src/component/navigation/style/module/_menu.scss
- src/component/navigation/style/scheme/_default.scss
- src/component/sidemenu/style/module/_action.scss
- src/component/sidemenu/style/module/_inner.scss
- src/component/sidemenu/style/module/_list.scss
- Uniformisation du menu latéral, navigation, et accordéon
- ajout d'un fond open-blue-france et du texte en blue-france sur les boutons d'ouverture en état ouvert
- ajout de marge pour indenter les sous menus
- ajustement des espacements
- Ajustement de la navigation du header en mobile
- Ajustement de la taille max de la navigation dans le header en desktop
> ✨ feat(navigation, header, sidemenu): homogénéisation des espacements et indentation [DS-3356]

- src/component/card/style/_scheme.scss
- src/component/tile/style/_scheme.scss
- le titre des cartes et tuiles doivent utiliser le token de couleur text-title-grey
> :bug: fix(card, tile): correctif token title [DS-3430]

- src/component/tooltip/example/sample/tooltip-text.ejs
- src/component/tooltip/script/tooltip/tooltip-referent.js
- src/component/tooltip/script/tooltip/tooltip.js
- src/component/tooltip/style/_module.scss
- src/component/tooltip/template/ejs/tooltip.ejs
- src/core/script/placement/placement-referent.js
- autorise le survol sur l'information contextuelle
- ajoute un `tabindex="0"` sur l'example dans un texte
- arrondi la valeur de placements de la flèche verticale à 2 décimales
- retire le `aria-hidden="true"` et ajoute `display="none"`
> 🐛 fix(tooltip) : a11y tooltip hover [DS-3461,DS-3462,DS-3463]

- src/analytics/doc/analytics/installation/configuration.md
- src/component/modal/script/modal/modal.js
- src/component/tooltip/script/tooltip/tooltip-referent.js
- src/core/index.js
- src/core/script/api/modules/register/instance.js
- src/core/script/api/modules/register/key-codes.js
- src/core/script/api/modules/stage/root-emission.js
- src/core/script/api/modules/stage/root-selector.js
- src/core/script/api/modules/stage/root.js
- Correctif à la pression de la touche Escape sur la modale : si l'élément actif (focus) est un élément de formulaire ou un média, la modale n'est pas refermée pas pour permettre l'interaction native de l'élément actif
- Correctif iOS de la prise de focus au clic
- Fermeture des tooltips dés au clic sur n'importe quel endroit
- Fermeture des tooltip à la pression sur la touche escape, où que soit le focus
> :bug: fix(tooltip,modal): interaction globale et focus iOS [DS-3460,DS-3395]

- module/color/variable/_decisions.scss
- Ajout des classes utilitaires pour le token background flat avec les variations de couleur d'accent
> :sparkles: feat(colors): ajout des utilitaires de couleur flat [DS-3484]

- src/component/sidemenu/style/_scheme.scss
- Effet de bord du passage du bouton mobile en bleu, l'ensemble des boutons du sidemenu est passé en bleu.
- Ce correctif amène la spécificité nécessaire pour avoir les boutons et lien en `text default grey`
> :bug: fix(sidemenu): correction de la couleur des liens du sidemenu [DS-3493]

- src/analytics/example/spa/agnostic/route.js.ejs
- src/component/form/style/module/_message.scss
- src/component/form/template/ejs/fieldset/fieldset.ejs
- src/component/form/template/ejs/message/builder.js.ejs
- src/component/input/input-base/template/ejs/input.ejs
- src/component/password/example/sample/password-register.ejs
- src/component/password/i18n/fr.yml
- src/component/password/style/_module.scss
- ajout sur les messages de validation et d'erreur de la composition du mot de passe d'un statut en after uniquement pour les lecteurs d'écrans
- BREAKING CHANGE : il est nécessaire d'ajouter les attributs `data-fr-valid`et `data-fr-error` avec les textes correspondants à l'état (respectivement, en français, "validé" et "en erreur"
> 🐛 fix(password): correctif accessibilité des messages [DS-3327]

- src/component/modal/style/_module.scss
- l'ajout d'un padding à l'ouverture permet de se substituer au décalage créé potentiellement par la disparition de la scrollbar en desktop
- En mobile, la modale occupe 100% de la largeur, ce padding créé un espacement incorrect
- ajout d'un media query sur le breakpoint MD pour corriger le problème
> 🐛 fix(modal): préviens décalage mobile [DS-3495]

- src/component/link/style/module/_download.scss
- les liens de téléchargement étaient limités à une seul ligne avec une ellipse sur le text dépassant
- correctif prenant en compte le retour à la ligne
> 🐛 fix(link): correctif téléchargement multiligne [DS-3509]

- src/component/toggle/style/module/_default.scss
- Au clic sur le toggle sur iOS, l'effet de highlight est présent
- Retrait de cet effet avec la propriété [-webkit-tap-highlight-color](https://developer.mozilla.org/fr/docs/Web/CSS/-webkit-tap-highlight-color)
> 🐛  fix(toggle): retrait tap-highlight-color iOS [DS-3502]

- README.md
- tool/example/example.ejs
- Sur iOS, les numéros de téléphone sont automatiquement transformés en lien
- Entraîne un mauvais rendu dans le bloc fonctionnel de numéro de téléphone
- Correction par l'ajout général du meta tag `<meta name="format-detection" content="telephone=no">`
> ✨ feat(*): Ajout d'un meta tag iOS [DS-3507]

- src/component/content/example/sample/media-default.ejs
- src/component/transcription/template/ejs/transcription.ejs
- Retrait du title sur le bouton agrandir
- Ajout label agrandir dans les exemples de content
> 🐛 fix(transcription, content): correctif title et label bouton Agrandir [DS-3512, DS-3501]

- src/component/password/style/_module.scss
- src/component/password/style/_scheme.scss
- src/core/style/action/module/_input.scss
- Dans les champs de type password, sur safari Mac, il y a une icône apportant des outils supplémentaire qui se superpose à l’icône des signalant la hauteur de casse
- Déplacement des icônes natives pour qu'elles ne se superposent pas
- Retrait de l'icône capslock native, privilégiant la nôtre
> ✨ feat(core, password): boutons spéciaux input Safari [DS-3510]

- src/component/modal/script/modal/modal.js
- Mise en place du retour du focus à la fermeture en pressant la touche ESC
> :bug: fix(modal): retour de focus fermeture clavier [DS-3513]

- src/component/consent/example/sample/modal/body.ejs
- Les cookies obligatoires doivent être systématiquement cochés
> 🐛 fix(consent): coche les cookies obligatoires par defaut [DS-3524]

- src/component/radio/style/scheme/_sm.scss
- Erreur dans le build du CSS suite au manque d'une couleur
> 🐛 fix(radio): correctif couleur manquante [DS-3558]

- src/component/link/style/module/_download.scss
- src/component/link/style/module/_group.scss
- Sur firefox, le détail passe sous le lien de téléchargement lorsque celui-ci est sur plusieurs lignes.
- Sur safari, les liens de téléchargement dans un groupe de lien sont décalés vers le bas.
> 🐛 fix(link): correction des liens de téléchargement sur firefox et des groupes de liens sur safari [DS-3569]

- src/component/consent/example/sample/modal/body.ejs
- src/component/header/style/module/_tools.scss
- passe le `max-width` de la barre de recherche à `96v` (`384px`)
> 🐛 fix(header): met a jour la taille de la barre de recherche [DS-3521]

- src/component/footer/example/index.ejs
- src/component/footer/example/sample/footer-partners.ejs
- src/component/footer/example/sample/footer.ejs
- src/component/footer/style/module/_partners.scss
- src/component/footer/template/ejs/partners.ejs
- ajoute un exemple avec logos partenaires secondaires uniquement
- a11y : corrige le niveau de titre des partenaires
> 🐛 fix(footer): correctifs logo partenaires [DS-3384, DS-3560]

- src/component/consent/template/ejs/placeholder.ejs
- le titre est passé de `<p>` à `<h4>` dans la structure HTML du composant
> 🐛 fix(consent): ajoute un niveau de titre sur la bannière de consentement [DS-2257]

- src/component/button/style/tool/_group.scss
- src/component/button/template/ejs/buttons-group.ejs
- src/component/modal/example/sample/footer/buttons.ejs
- retrait de la liste `<ul><li>` dans la structure HTML de la zone d'action qui devient : 
```
<div class="fr-modal__footer">
<div class="fr-btns-group fr-btns-group--right fr-btns-group--inline-reverse fr-btns-group--inline-lg fr-btns-group--icon-left">
<button class="fr-btn fr-icon-checkbox-circle-line fr-btn--icon-left" id="button-5462">
Label bouton
</button>
<button class="fr-btn fr-icon-checkbox-circle-line fr-btn--icon-left fr-btn--secondary" id="button-5463">
Label bouton
</button>
</div>
</div>
```
> 🐛 fix(modal): a11y retire la liste dans la zone d'actions [DS-1257]

- src/component/select/example/index.ejs
- src/component/select/example/sample/option-group.ejs
- src/component/select/template/ejs/select.ejs
- L'élément HTML `<optgroup>`, utilisé dans un formulaire, permet de créer un groupe d'options parmi lesquelles on peut choisir dans un élément `<select>`.
> ✨ feat(select): ajout exemple `<optgroup>` [DS-3374]

- src/analytics/example/attribute/index.ejs
- src/analytics/example/component/quote/index.ejs
- src/component/button/template/ejs/button.ejs
- src/component/card/example/sample/card-default.ejs
- src/component/card/template/ejs/content.ejs
- src/component/display/deprecated/example/index.ejs
- src/component/display/example/index.ejs
- src/component/footer/example/sample/footer.ejs
- src/component/footer/template/ejs/content.ejs
- src/component/link/deprecated/template/ejs/link.ejs
- src/component/link/template/ejs/link.ejs
- src/component/navigation/template/ejs/link.ejs
- src/component/notice/example/index.ejs
- src/component/quote/example/sample/quote-default.ejs
- src/component/tag/template/ejs/tag.ejs
- src/component/tile/example/sample/tile-default.ejs
- src/component/tile/template/ejs/content.ejs
- src/core/example/link/link-raw/index.ejs
- src/core/example/link/link-reset/index.ejs
- src/core/example/reset/index.ejs
- tool/example/decorator.ejs
- tool/example/heading.ejs
Ajout de l'attribut rel="noopener" et title="intitulé - nouvelle fenêtre" à tous les liens en target="_blank"
+ correction tuile avec lien externe
> ♻️ refactor(link): rel noopener & title target blank  [DS-2509]

- src/component/alert/style/_module.scss
- src/component/alert/style/_scheme.scss
- refactorisation de la bordure des alertes en background-image à la place de box-shadow
> ♻️ refactor(alert): bordures en background-image [DS-3360]

- src/component/header/style/_scheme.scss
- Le titre de service doit passer en text title default
> 🐛 fix(header): Token de couleur du texte de service en title grey [DS-3520]

- src/component/callout/style/_module.scss
- src/component/callout/style/_scheme.scss
- src/component/highlight/style/_module.scss
- src/component/highlight/style/_scheme.scss
Les bordures de la mise en avant et mise en exergue sont actuellement en box-shadow, les passer en background-image
> ♻️ refactor(highlight, callout): background image à la place de box shadow [DS-3361]

- module/selector/_index.scss
- module/selector/mixin/_current.scss
- src/component/breadcrumb/style/_legacy.scss
- src/component/breadcrumb/style/_module.scss
- src/component/breadcrumb/style/_scheme.scss
- src/component/navigation/style/module/_default.scss
- src/component/navigation/style/scheme/_default.scss
- src/component/pagination/style/_contrast-scheme.scss
- src/component/pagination/style/_contrast.scss
- src/component/pagination/style/_module.scss
- src/component/pagination/style/_scheme.scss
- src/component/sidemenu/style/_scheme.scss
- src/component/sidemenu/style/module/_action.scss
- src/component/translate/style/_module.scss
- correctif lorsque l'attribut [aria-current] est à "false"
> 🐛 fix(breadcrumb, navigation, pagination, sidemenu, translate): selecteur aria-current [DS-3566]

- src/component/skiplink/style/_module.scss
- cache le skiplink lors du rebond du scroll sur ios
> 🐛 fix(skiplink): visible avec elastic scrolling [DS-3052]

- src/component/password/style/_scheme.scss
- utilisation du token de couleur : text-label-grey
> 🐛 fix(password): couleur du texte de la checkbox afficher [DS-3567]

- src/page/account/login/example/data/login.json.ejs
- src/page/account/login/example/sample/default.ejs
- corrige l'espace en trop entre le lien "Mot de passe oublié ?" et la checkbox "Se souvenir de moi",
- ajoute une marge supplémentaire sous l’alerte d’erreur
> 🐛 fix(login): corrige espacements [DS-3400]

- src/component/checkbox/style/_scheme.scss
- src/component/consent/example/sample/modal/body.ejs
- passe la couleur de la coche en `$text-inverted-blue-france`
> 🐛 fix(checkbox): met a jour le token de la coche [DS-3472]

- src/component/consent/example/sample/modal/body.ejs
- src/component/form/deprecated/style/_module.scss
- src/component/input/input-base/style/_module.scss
- place l’icône à 16px du bord droit des champs de saisie
- ajuste le `padding-right` à 44px sur les champs de saisie avec icône
- corrige la largeur des class `fr-fieldset__content` pour la version dépréciée
> 🐛 fix(form, input): met a jour les espacements des icônes [DS-3474, DS-3504]

- src/component/consent/example/sample/modal/body.ejs
- src/component/consent/style/module/_services.scss
- Les sous finalités ont une marge plus importantes à droite sur le radio Accepter
> 🐛 fix(consent): correction espacement des radios accepter [DS-3525]

- src/component/toggle/style/_scheme.scss
- src/component/toggle/style/module/_default.scss
- utilisation du token de couleur $text-label-grey sur le label de l'interrupteur 
- ajout de 4px de marge entre la coche et le texte activer/desactiver
> 🐛 fix(toggle): couleur label & espacement activer/desactiver [DS-3526, DS-3527]

- src/component/input/input-base/style/_scheme.scss
- Lorsque le champ newsletter de la lettre d'information est en erreur le champs doit être souligné en rouge et non en bleu
> 🐛 fix(input): combo champ + button en erreur [DS-3583]

- src/component/consent/example/sample/modal/body.ejs
- src/core/.package.yml
- met à jour le lien vers la page [Typographie](https://www.systeme-de-design.gouv.fr/elements-d-interface/fondamentaux-de-l-identite-de-l-etat/typographie/) du site de documentation.
> 🐛 fix(core): mise à jour de lien [DS-3588]

- src/component/summary/style/_module.scss
- Ajout d'un padding-left de 8px pour aligner le titre avec le premier élément de la liste
> 🐛 fix(summary): alignement du titre du sommaire [DS-3555]

- src/component/tag/style/_scheme.scss
- Utilisation du token $text-inverted-blue-france sur la couleur du texte des tag selectionnable et supprimable à la place de $text-inverted-grey
- Remplacement du token de couleur de fond des tag selectionnable par $background-active-blue-france au lieu de $background-action-high-blue-france
> 🐛 fix(tag): token de couleur du tag selectionnable [DS-3556]

- src/component/consent/example/sample/modal/body.ejs
- src/component/follow/example/data/socials.json.ejs
- src/component/follow/style/_module.scss
- src/component/follow/template/ejs/newsletter.ejs
- inverse l'ordre des boutons "Instagram" et "LinkedIn"
- supprimer les margin left et right du groupe de boutons
- place le bouton d'action dans un groupe de bouton `fr-btns-group--inline-md` sur les exemples "Lettre d'info seule" et "Réseaux sociaux et Lettre d'info mise en avant" pour que le bouton prenne l’ensemble de la largeur en vue mobile.
> 🐛 fix(follow): corrige affichage [DS-3529, DS-3531, DS-3532]

- src/component/skiplink/style/_module.scss
- L'ecart entre les liens d'évitement passe à 16px (4v)
- En desktop la marge en haut et en bas du composant passe à 12px (3v)
> 🐛 fix(skiplink): espacements des liens d'évitement [DS-3533]

- src/component/form/style/_scheme.scss
- la légende d'un fieldset passe en $text-label-grey à la place de $text-title-grey
> 🐛 fix(form): token de couleur de la legend [DS-3550]

- src/component/alert/style/_module.scss
- src/component/button/style/module/_close.scss
- src/component/consent/example/sample/modal/body.ejs
- src/component/navigation/style/module/_mega-menu.scss
- src/component/notice/style/_module.scss
- retire le `margin-right: -1rem` sur le modifier `.fr-btn--close` et corrige l'impact sur les composants `fr-alert`, `fr-navigation`, et `fr-notice`
> 🐛 fix(close-btn): retire le `margin-left` négatif [DS-3522]

- src/component/consent/example/sample/modal/body.ejs
- src/component/navigation/index.scss
- src/component/navigation/style/module/_mega-menu.scss
- src/component/navigation/style/scheme/_default.scss
- src/component/navigation/template/ejs/leader.ejs
- ajoute un `margin-top: -1.25rem` (-20px) sur le `fr-mega-menu__leader`
- passe le texte de description et le lien du `fr-mega-menu__leader` en taille `sm`
- supprime la classe `fr-mb-4v `de la colonne entourant le `fr-mega-menu__leader`
- le texte du bouton de navigation passe en $text-action-high-blue-france à l'ouverture
> 🐛 fix(navigation): correctifs de style mega-menu [DS-3549, DS-3548]

- src/component/consent/example/sample/modal/body.ejs
- src/component/highlight/style/_module.scss
- passe le `padding` à `5v` en mobile et `9v` en desktop.
> 🐛 fix(highlight): met à jour les espacements [DS-3538]

- src/component/download/deprecated/style/module/_variants.scss
- Correction de css invalide -> double pseudo élément dans le css de 'download'
> 🐛 fix(download): icon-size bug compilation [DS-3593]

- src/component/footer/example/index.ejs
- src/component/footer/example/sample/footer-partners.ejs
- src/component/footer/example/sample/footer.ejs
- src/component/footer/style/_scheme.scss
- src/component/footer/style/module/_bottom.scss
- src/component/footer/style/module/_content.scss
- src/component/footer/style/module/_default.scss
- src/component/footer/style/module/_partners.scss
- src/component/footer/style/module/_top.scss
- src/component/footer/template/ejs/partners.ejs
- le texte filler de footer__content-desc doit faire maximum 3 lignes en desktop
- passe les liens .fr-footer__content-link en $text-default-grey
- passe le padding top de .fr-footer__bottom-list à 4v
- correction des espacements autour de fr-footer-body :  en mobile et en desktop (32px en haut et 24px en bas)
- titre “nos partenaire“ → fr-footer__partners-title passe en graisse régular, couleur text-default-grey
- ecart de 12px sous “Nos partenaire” en mobile/desktop
- enleve le padding sur .fr-footer__partners .fr-footer__logo, ajoute une border 1px en $border-default-grey + un background en background-default-grey
- en desktop l’ecart entre logo et bloc mark passe à 32px
- passe le logo opérateur en 16x9
- ajoute un margin bottom négatif de 8px sur le groupe de lien pour garder 24px en …
> 🐛 fix(footer): ajustements [DS-3552, DS-3384, DS-3560, DS-3381]

- src/component/sidemenu/style/module/_inner.scss
- retire 1v de padding gauche et droite sur `fr-sidemenu__inner` en desktop
> 🐛 fix(sidemenu): correction marge interne [DS-3537]

- src/component/card/style/module/_default.scss
- src/scheme/script/scheme/scheme.js
Sur les anciennes version de safari macOS (inférieure à 14.0)
- corrige l'alignement du détail de la carte dans une grille de carte
- corrige une erreur de javascript sur `scheme.js`
> 🐛 fix(card): alignement du détail & erreur js sur safari <14 [DS-3191]

- README.md
Le lien actuel renvoit vers une page d'erreur 404
> 📝 doc(readme): correction du lien de la documentation des icônes

- src/component/connect/i18n/fr.yml
- src/component/connect/standalone/style/_module.scss
- src/component/connect/style/module/_agent.scss
- src/component/connect/style/module/_default.scss
- src/component/connect/style/module/_plus.scss
- src/component/connect/style/scheme/_default.scss
- src/component/connect/style/setting/_size.scss
- src/core/style/action/tool/_button.scss
Actuellement, le bouton FranceConnect ne répond pas aux critères d’accessibilité qui redéfinisse le letter-spacing et la taille de fonte.
- Passage des valeurs de tailles et d'espacements en 'em' pour les rendre relatives à la taille de fonte du bouton.
- **Retrait du '+' de 'FranceConnect+' dans l'intitulé de `fr-connect__brand`**. Celui-ci est désormais placé en contenu du pseudo-élément after du bouton
> 🐛 fix(connect): adaptabilité de la taille de fonte pour l'accessibilité [DS-3627]

- README.md
- correction d'espacements et de fautes de frappe
- précise l'interdiction d'utilisation "pour des sites web ou des applications", sans interdire d'utiliser le DSFR pour
créer, par exemple, un système de design entièrement différent (d'où l'intérêt de la licence libre).
> 📝 doc(readme): mise en forme et précision du README.md

- src/component/toggle/example/sample/toggle-default.ejs
- src/component/toggle/example/sample/toggle-group.ejs
- src/component/toggle/style/module/_default.scss
- src/component/toggle/style/module/_variants.scss
- augmentation de la largeur max du label, la marge de 10v passe à 8v
- changement du libellé du label et du texte additionnel
> 🐛 fix(toggle): largeur max du label & libellé [DS-3647]

- tool/example/heading.ejs
- correction des liens de la documentation qui ne s'affichent plus dans les exemples
> 🐛 fix(build): liens doc sur core & utility [DS-3652]

- src/component/card/style/module/_content.scss
- src/component/card/template/ejs/content.ejs
- src/component/link/example/index.ejs
- src/component/link/template/ejs/link.ejs
- src/component/tile/style/module/_default.scss
- src/component/tile/template/ejs/content.ejs
- retrait du saut de ligne entre la balise `a` et son libellé pour corriger l'écart entre le libellé du lien et l'icone
- ajout d'un exemple "lien externe" dans les exemples de lien
- correction de la taille de l'icone sur les tuiles sans lien étendu
- retrait de l'icone arrow-right sur les tuiles sans lien étendu, pour être iso avec les cartes
> 🐛 fix(link, card, tile): espacement entre libellé et icone [DS-3643]

- src/component/range/.package.yml
- src/component/range/script/range/range.js
- Le composant `range`utilise des fonctionnalités de `scheme` pour pouvoir passer en dark mode
- Ajout de la dépendance dans la configuration du package `range`
- Vérification de l'implémentation (optionnelle) de `scheme` avant d'en utiliser les fonctionnalités
> 🐛 fix(range): dépendance à scheme [DS-3641]

- src/component/breadcrumb/style/_module.scss
- src/component/button/style/_legacy.scss
- src/component/card/style/_legacy.scss
- src/component/card/template/ejs/header.ejs
- src/component/checkbox/deprecated/style/_module.scss
- src/component/checkbox/style/_legacy.scss
- src/component/connect/style/module/_plus.scss
- src/component/header/style/_legacy.scss
- src/component/pagination/style/_legacy.scss
- src/component/quote/style/_legacy.scss
- src/component/range/style/_legacy.scss
- src/component/segmented/style/_legacy.scss
- src/component/tag/style/_legacy.scss
- src/component/tag/style/_scheme.scss
- src/core/style/action/legacy/_link.scss
- src/core/style/typography/_legacy.scss
- Retrait du soulignement sur les bouton et tags en `a` sur IE
- Retrait de la marge top des paragraphes `p` sur IE
- Changement du placement du '+' de franceConnect+
- Correction du ratio d'image sur les cartes de téléchargement sur IE
- Réglage de l'alignement de l'icône des liens en target blank sur IE
- Correction de l'alignement de la case des cases à cocher sur IE
- Correction des min/max/valeur du curseur sur IE
- Retrait du focus autour de l'icône des controles segmentés sur IE
- Correction de la hauteur du composant fil d'arianne sur IE
- Ajout des modifiers de bouton pour les accès rapide du header sur IE
- Correction des icones prev/next de la pagination sur IE
- Correction des couleurs du tag désactivé sur IE
- Retrait du soulignement dans le reset des liens `a`
> 🐛 fix(legacy): bugs IE divers [DS-3641]

- module/elevation/variable/_z-indexes.scss
- src/component/header/style/_scheme.scss
- ajout d'un niveau d'élévation `raised-over`
- le header passe en z-index `raised-over`
> 🐛 fix(header): augmente le z-index du header [DS-3661]

- src/analytics/example/spa/agnostic/route.js.ejs
- src/analytics/script/integration/component/component-actionee.js
- src/analytics/script/integration/core/actionee.js
- src/component/header/script/header/header-modal.js
- src/component/navigation/script/navigation/navigation.js
- corrige un bug de fermeture au clic à l'extérieur du composant sur safari
- corrige un bug de fermeture d'un volet au clic sur un lien ou un bouton à l'intérieur du composant
> 🐛 fix(navigation): corrige bugs de fermeture du composant [DS-3617, DS-3619]

- src/component/connect/style/module/_default.scss
- src/component/footer/style/module/_default.scss
- src/component/footer/style/module/_partners.scss
- src/component/header/style/module/_brand.scss
- retrait de l'icone "external link" sur les liens en target blank du :
- lien des logos du footer
- lien sur le nom de service du header
- bouton franceConnect s'il est sous forme de lien
> 🐛 fix(footer, header, connect): retrait de l'icone target blank [DS-3715]

- src/core/style/reset/_module.scss
- src/core/style/reset/module/_select.scss
- ajoute un `font-style: normal` sur `optgroup` dans le reset
> 🐛 fix(select): corrige l'affichage du optgroup sur firefox windows [DS-3712]

- src/analytics/doc/analytics/collector/site.md
- src/analytics/example/config.ejs
- src/analytics/script/analytics/collector/site/site.js
- ajouts de la propriété de version du site dans les données de mesure d'audience
> ✨ feat(analytics): ajout de la version du site [DS-3718]

- src/analytics/example/spa/agnostic/index.ejs
- src/analytics/example/spa/angular/_index.ejs
- src/analytics/example/spa/react/index.ejs
- src/analytics/example/spa/vue/index.ejs
- src/component/header/deprecated/template/ejs/navbar.ejs
- src/component/header/template/ejs/navbar.ejs
- Retrait de l'attribut `aria-haspopup` du bouton du burger menu en mobile
> ✨ feat(header): retire aria attribut haspopup du burger menu en mobile [DS-3679]

- src/component/header/style/module/_modal.scss
- retire le `overflow: hidden;` sur le `fr-container` du champ de recherche
> 🐛 fix(header): corrige le focus sur le champ de recherche [DS-3499]

- src/component/alert/example/index.ejs
- Ajout d’exemples d’alerte MD sans titre, et d’alerte SM avec titre
> ✨ feat(alert): ajoute un example de taille md avec description seule [DS-3685, DS-3688]

- src/component/header/style/module/_brand.scss
- correction du focus caché par un overflow hidden, sur le lien du logo du header
> 🐛 fix(header): focus caché sur le lien du logo [DS-3723]

- src/analytics/script/integration/component/breadcrumb/breadcrumb-link-actionee.js
- src/analytics/script/integration/component/button/button-actionee.js
- src/analytics/script/integration/component/card/card-actionee.js
- src/analytics/script/integration/component/connect/connect-actionee.js
- src/analytics/script/integration/component/connect/connect-link-actionee.js
- src/analytics/script/integration/component/download/download-actionee.js
- src/analytics/script/integration/component/footer/footer-link-actionee.js
- src/analytics/script/integration/component/link/link-actionee.js
- src/analytics/script/integration/component/navigation/navigation-link-actionee.js
- src/analytics/script/integration/component/pagination/pagination-link-actionee.js
- src/analytics/script/integration/component/sidemenu/sidemenu-link-actionee.js
- src/analytics/script/integration/component/summary/summary-link-actionee.js
- src/analytics/script/integration/component/tag/tag-actionee.js
- src/analytics/script/integration/component/tile/tile-actionee.js
- src/analytics/script/integration/core/action/a-actionee.js
- src/analytics/script/integration/core/actionee.js
- src/core/script/api/modules/register/instance.js
- corrige un bug js au niveau de l'héritage du listenClick. Renommage de la fonction listenClick en listenActionClick car la fonction existe déja sur la classe héritée "Instance"
> 🐛  fix(analytics): correctif héritage listenClick [DS-3745]

- src/core/style/reset/module/_body.scss
- Ajout de la propriété `overflow-wrap: world-break` sur body permettant le passage à la ligne des mots plus grand que leur conteneur.
> ✨ feat(core): ajout d'un retour à la ligne des mots trop long [DS-3737]

- src/component/tag/style/_scheme.scss
- Le hover des tags cliquables avait disparu
> 🐛 fix(tag): corrige le hover des tags cliquables [DS-3724]

- src/analytics/doc/analytics/installation/configuration.md
- Ajoute dans la doc de configuration des analytics, la possibilité de surcharger la configuration du mode production via le paramètre dans l'url : `?production=false`
> ✨ feat(doc): ajout d'infos sur la configuration dans la doc analytics [DS-3741]

- src/component/header/script/header/header-links.js
- la valeur null renvoyée par la fonction match est remplacée par un array vide pour permettre son itération
- Corrige #890
> 🐛 fix(header): correctif erreur itérable null [DS-3747]

- package.json
- yarn.lock
> ⬆️ chore(dependencies): met a jour la dépendance postCSS

- src/analytics/doc/analytics.md
- src/analytics/doc/analytics/actions.md
- src/analytics/doc/analytics/collector.md
- src/analytics/doc/analytics/installation.md
- src/analytics/standalone/api.js
- src/analytics/standalone/config.js
- src/analytics/standalone/example/index.ejs
- src/core/script/api/api.js
- src/core/script/api/options/modes.js
- src/core/script/api/options/options.js
- correctifs dans la version standalone : 
- configuration appliquée au logging (`verbose`, `production`)
- retrait de dépendances non requises
- ajout de documentation sur la version standalone
- installation
- fonctionnalités disponibles
- Extraction de `Modes` du fichier de la class `Options` pour réduire les dépendances
- Apporte des éléments correctifs à #880
> 🐛 fix(analytics): documentation et correctif version standalone [DS-3746]

- src/component/breadcrumb/style/_module.scss
- corrige l'alignement vertical des icônes de chevron sur tout les navigateurs (bug sur Safari 17)
> 🐛 fix(breadcrumb): alignement vertical des icônes de chevron [DS-3779]

- src/component/range/example/index.ejs
- src/component/range/example/sample/range.ejs
- src/component/range/i18n/fr.yml
- src/component/range/script/range/range-input.js
- src/component/range/script/range/range-input2.js
- src/component/range/script/range/range-model.js
- src/component/range/style/_scheme.scss
- src/component/range/template/ejs/range.ejs
- corrige la boucle infinie qui fait crash la page lorsque stepwidth = 0
- corrige le style du curseur avec étape désactivé
- ajout d'exemples de curseurs double désactivé et avec étape désactivé
- corrige la modification de valeur du deuxième input lorsque le min dépasse le max ou l'inverse sur le curseur double
> 🐛 fix(range): bug js boucle infinie et step désactivé [DS-3739, DS-3777]

- src/component/quote/style/_module.scss
- ajout de la propriété `object-fit: cover` sur l'image de citation pour conserver le ratio de l'image lorsqu'elle n'est pas carrée. 
- dans la mesure du possible, privilégiez un ratio d'image carré pour un meilleur support navigateur
> 🐛 fix(quote): ratio de l'image de citation [DS-3767]

- README.md
- package.json
- tool/build/build.js
- lors de l'execution de la commande `yarn build`, crée les fichiers de configuration s'ils n'existent pas
- ajout de browser-sync en tant que peerDependencies dans le package.json
- ajout de précision sur le lancement du serveur des pages d'exemple dans le README
> ✨ feat(build): ajoute la config au premier build & precision readme [DS-3681]

- src/component/footer/example/sample/footer.ejs
- src/component/footer/template/ejs/content.ejs
- tool/example/decorator.ejs
- remplace l'intitulé par défaut "[A modifier]" de l'attribut title par l'intitulé officiel sur les liens obligatoires du footer.
- **Change l'ordre des liens, et gouvernement.fr devient info.gouv.fr**
> 🐛 fix(footer): title des liens obligatoires du footer [DS-3760, DS-3789]

- src/analytics/doc/analytics.md
- src/analytics/doc/analytics/actions.md
- src/analytics/doc/analytics/collector/analytics.md
- src/analytics/example/action/index.ejs
- src/analytics/example/config.ejs
- src/analytics/i18n/fr.yml
- src/analytics/script/analytics/action/action-element.js
- src/analytics/script/analytics/action/action-regulation.js
- src/analytics/script/analytics/action/action.js
- src/analytics/script/analytics/engine/queue.js
- src/analytics/script/integration/core/actionee.js
- ajout de la possibilité de bloquer une action particulière avec l'attribut et la valeur `data-fr-analytics-action="false"` quand l'envoi des actions est activé au global via la config isActionEnabled: true
> ✨ feat(analytics): système de régulation des actions [DS-3799]

- src/component/footer/style/module/_default.scss
- src/component/header/style/_scheme.scss
- src/component/header/style/module/_brand.scss
- src/component/header/style/module/_navbar.scss
- sur le header mobile la partie à droite du brand n'est plus cliquable pour éviter les clics manqués sur le burger ou la recherche, et le lien du nom de service n'est plus étendu sur toute la largeur
- sur le footer mobile la zone de clic n'est plus étendu sur toute la largeur
> 🐛 fix(footer, header): réduction de la zone de clic retour à l'accueil [DS-3800]

- src/component/card/example/index.ejs
- src/component/card/example/sample/sample-disabled.ejs
- src/component/card/style/_legacy.scss
- src/component/card/style/module/_content.scss
- src/component/card/style/module/_default.scss
- src/component/card/style/module/_download.scss
- src/component/card/style/module/_header.scss
- src/component/card/style/module/_lg.scss
- src/component/card/style/module/_sm.scss
- src/component/card/template/ejs/card.ejs
- src/component/card/template/ejs/content.ejs
- src/component/link/template/ejs/link.ejs
- src/component/tile/example/index.ejs
- src/component/tile/example/sample/sample-disabled.ejs
- src/component/tile/style/_legacy.scss
- src/component/tile/style/_scheme.scss
- src/component/tile/style/_tool.scss
- src/component/tile/style/module/_default.scss
- src/component/tile/style/module/_download.scss
- src/component/tile/style/module/_sm.scss
- src/component/tile/template/ejs/content.ejs
- src/component/tile/template/ejs/tile.ejs
- src/core/style/action/_module.scss
- src/core/style/action/legacy/_hover.scss
- src/core/style/action/module/_enlarge.scss
- src/core/template/ejs/action/action.ejs
- ajoute une classe utilitaire `enlarge-button` utilisée sur les cartes et les tuiles de téléchargement pour élargir la zone de clique à tout le composant quand l'element cliquable est un bouton
> 🐛 fix(link, card, tile): enlarge button [DS-3798]

- src/component/input/input-base/example/sample/inputs.ejs
- src/component/modal/example/sample/body/form.ejs
- src/component/modal/script/modal/focus-trap.js
- Correction d'une erreur js lorsqu'un champs de saisie n'a pas d'attribut "type" à l'ouverture d'une modale
> 🐛 fix(modal): input sans type bug dans le focus trap de la modale [DS-3831]

- src/core/style/action/setting/_elements.scss
- Correction de l'opacité du texte des listes déroulantes (select) désactivées ( fix #994 )
> 🐛 fix(core): opacité du texte du select désactivé

- package.json
- yarn.lock
- Modifie la version de la dépendance à BrowserSync dans le package.json, permettant l'utilisation d'une version plus récente #975
> ✨ fix(build): browsersync dependency >=2.27 [DS-3845]

- src/analytics/doc/analytics/collector/page.md
- Correction de la valeur, si non renseignée, du paramètre page.path dans la documentation analytics
> 🐛 fix(anayltics): correction doc page.path [DS-3823]

- README.md
- correction du nom du fichier utility.min.css dans le readme
> 🐛 fix(readme): correction nom fichier utility [DS-3830]

- src/component/notice/style/_module.scss
- correction du style du titre du bandeau lors de l'utilisation d'un niveau d'entête hx à la place de la balise p
> 🐛 fix(notice): correction css markup hx sur le titre du bandeau [DS-3840]

- src/analytics/example/action/index.ejs
- src/analytics/example/spa/agnostic/index.ejs
- src/analytics/example/spa/agnostic/route.js.ejs
- src/analytics/example/spa/angular/_index.ejs
- src/analytics/example/spa/react/index.ejs
- src/analytics/example/spa/vue/index.ejs
- src/component/accordion/template/ejs/accordion.ejs
- src/component/alert/example/layout-dynamic.ejs
- src/component/breadcrumb/template/ejs/breadcrumb.ejs
- src/component/button/template/ejs/button.ejs
- src/component/card/template/ejs/content.ejs
- src/component/connect/example/data/connect.json.ejs
- src/component/connect/example/index.ejs
- src/component/connect/example/sample/connect-agent.ejs
- src/component/connect/example/sample/connect-plus.ejs
- src/component/connect/template/ejs/connect.ejs
- src/component/consent/template/ejs/manager.ejs
- src/component/display/deprecated/example/index.ejs
- src/component/follow/example/data/newsletter-form.json.ejs
- src/component/input/input-base/example/sample/inputs.ejs
- src/component/modal/example/sample/body/form.ejs
- src/component/navigation/template/ejs/btn.ejs
- src/component/sidemenu/template/ejs/btn.ejs
- src/component/sidemenu/template/ejs/sidemenu.ejs
- src/component/tab/template/ejs/tab.ejs
- src/component/tag/template/ejs/tag.ejs
- src/component/tile/template/ejs/content.ejs
- src/component/transcription/template/ejs/transcription.ejs
- src/page/account/login/example/data/login.json.ejs
- tool/example/controls.ejs
- ajoute le type `button` aux boutons par défaut
- met à jour les exemples des modèles de pages analytics et page de connexion
- met à jour les snippets d'exemple des composants : accordéon, alerte, fil d'ariane, bouton, bouton France Connect, carte, gestionnaire de consentement, paramètres d'affichage, champ de saisie, lettre d'information, navigation principale, menu latéral, onglets, tag, tuile et transcription
- remplace l'attribut `type` par `variant` dans le template du Bouton France Connect et ajoute le type `button` par défaut
> 🐛 fix(button): ajoute le type button par défaut [DS-3828]

- src/component/link/deprecated/style/module/_close.scss
- Correction de l'alignement vertical de l'icone du lien de fermeture déprécié (maintenant btn-close)
> 🐛 fix(link): alignement icone link close deprécié [DS-3837]

- src/component/notice/style/_module.scss
- Retire le padding à droite du bandeau lorsqu'il n'y a pas de bouton de fermeture.
> 🐛 fix(notice): padding notice sans close btn [DS-3848]

- src/core/style/collapse/_tool.scss
- Ajout d'un overflow auto sur le collapse pour éviter le passage des menus sous des éléments survolés ou le texte surligné #1014
> 🐛 fix(core): bug firefox menu passe en arrière plan [DS-3852]

- src/component/button/style/_legacy.scss
- src/component/button/style/module/_sort.scss
- src/component/table/example/data/data-miscellaneous.json.ejs
- remplace l'attribut `aria-sorting` par `aria-sort` sur les bouton de tri avec comme valeurs `descending` et `ascending` ( fix #1026 )
- met à jour la page d'exemple des tableaux
> 🐛 💥 fix(table): correction de l'attribut aria-sort [DS-3858]

- src/component/modal/.package.yml
- src/component/modal/example/index.ejs
- src/component/modal/example/sample/body/table.ejs
- src/component/modal/style/_module.scss
- passe le footer de la modale au niveau "overlap-above" permettant d'être au dessus du tooltip ( fix #978 )
- ajoute un exemple de modale comportant une zone d'actions et un tableau long
> 🐛 fix(modal): correction modal footer z-index [DS-3839]

- src/component/range/script/range/range-input.js
- src/component/range/script/range/range-input2.js
- src/core/script/action/toggle/toggle.js
- src/core/script/api/engine.js
- src/core/script/api/modules/register/Instance-event.js
- src/core/script/api/modules/register/instance.js
- src/core/script/api/modules/render/renderer.js
- src/core/script/api/modules/resize/resizer.js
- src/core/script/api/modules/scroll/scroll-locker.js
- src/core/script/api/modules/stage/root-event.js
- src/core/script/api/options/options.js
- src/core/script/api/utilities/dom/dispatch.js
- src/core/script/api/utilities/dom/index.js
- src/core/script/disclosure/disclosure-event.js
- src/core/script/disclosure/disclosure.js
- src/core/script/disclosure/disclosures-group.js
- src/scheme/script/scheme/scheme.js
Ajout des événements : 
Sur le éléments root (documentElement) :
- dsfr.ready : lorsque le js est chargé
- dsfr.start : au démarrage du moteur js du dsfr
- dsfr.stop : à l'arrêt du moteur js du dsfr
- dsfr.render : lors du rendu d'une instance
- dsfr.resize : lors du changement de taille du viewport
- dsfr.scroll-lock : au blocage du scroll
- dsfr.scroll-unlock : au déblocage du scroll
- dsfr.scheme : au chargement et changement du scheme (dark, light, auto)
- dsfr.theme : au chargement et changement du theme (light, dark)
Au niveau des instances, et remontées aux parents jusqu'au documentElement :
- dsfr.click : au click sur un bouton
- dsfr.disclose : à l'ouverture d'un disclosure
- dsfr.conceal : à la fermeture d'un disclosure
- dsfr.current : retourne l'élément ouvert d'un groupe de …
> ✨ feat(api): ajouts d'évènements dans l'api [DS-2052]

- src/core/script/disclosure/disclosures-group.js
- Correction lorsque tous les disclosures d'un groupe avec l'attribut group="false" sont ouverts au chargement #1024
> 🐛 fix(accordion): ouverture initiale des accordéons dégroupés [DS-3860]

- src/component/range/script/range/range-input.js
- src/component/range/script/range/range-input2.js
- Le composant est mis à jour graphiquement au changement de value des inputs en js.
> 🐛 fix(range): ajout de la possibilité de changer la value en JS [DS-3853]

- src/dsfr/component/table/style/_scheme.scss
- src/dsfr/component/table/style/module/_variants.scss
- Correction de la bordure lorsqu'un rowspan est en dernière position. #1035
> 🐛 fix(table): bordure disparait lors d'un rowspan en dernière position [DS-3862] 

- src/dsfr/component/navigation/style/module/_default.scss
- src/dsfr/component/navigation/style/module/_mega-menu.scss
- src/dsfr/component/navigation/style/module/_menu.scss
- src/dsfr/component/navigation/style/scheme/_menu.scss
- src/dsfr/component/tile/style/module/_default.scss
- Retrait des selecteurs d'enfants directs pour éviter les problèmes lors de l'ajout de balises intermediaires (cas de création de sous composants)
> 🐛 fix(tile, navigation): retrait des sélecteur css ">"

- src/component/radio/style/module/_rich.scss
- src/component/radio/style/module/_sm.scss
- src/dsfr/utility/colors/.package.yml
- src/dsfr/utility/colors/_index.scss
- src/dsfr/utility/colors/_setting.scss
- src/dsfr/utility/colors/example/background/index.ejs
- src/dsfr/utility/colors/example/border/index.ejs
- src/dsfr/utility/colors/example/index.ejs
- src/dsfr/utility/colors/example/sample/default.ejs
- src/dsfr/utility/colors/example/text/index.ejs
- src/dsfr/utility/colors/i18n/fr.yml
- src/dsfr/utility/colors/mixin/_border.scss
- src/dsfr/utility/colors/mixin/_scheme.scss
- src/module/color/variable/_decisions.scss
- src/module/color/variable/_sets.scss
- tool/generate/colors.js
- tool/generate/config.js
- Ajoute au build la generation d'un json des colors
- Ajoute des classes utilitaire de bordure (couleur et épaisseur)
- Ajoute des pages d'exemple d'utilisation des classes utilitaires des couleurs de background, texte et bordure
- Ajoute une page d'exemple d'utilisation des classes utilitaires de largeur de bordures
> ✨ feat(colors) : page d'exemple utilitaires de couleurs [DS-2763]

- yarn.lock
- bump cross-spawn from 7.0.3 to 7.0.6
- bump micromatch from 4.0.5 to 4.0.8
- bump semver from 7.3.5 to 7.6.2
- bump ws from 7.5.9 to 7.5.10
> ⬆️ chore(dependencies): mise à jour des dépendances npm

- src/dsfr/component/tooltip/template/stories/tooltip.stories.js
- Corrige l'affichage du tooltip sur la story par défaut,
- Ajoute une story pour l'infobulle actionnable au clic.
> 🐛 fix(storybook): corrige tooltip [DSFR-53]

- src/dsfr/component/notice/template/ejs/notice.ejs
- src/dsfr/component/notice/template/stories/notice-arg-types.js
Dans le storybook, le nom du type de bandeau utilisé pour les alertes attentat est incorrect. 
`vigipirate` -> `attack`
> 🐛 fix(storybook): nom du type de bandeau attentat dans le storybook

- src/dsfr/component/accordion/example/sample/accordions-group.ejs
- src/dsfr/core/script/disclosure/disclosure.js
- Pour les composants de type closure, l'événement de fermeture n'est plus lancé au chargement du composant (accordion, modal, etc)
> 🐛 fix(core): disclosure evenement dsfr.conceal [DSFR-71]

- src/dsfr/component/select/template/ejs/select.ejs
BREAKING CHANGE :
- Retrait de l'attribut hidden sur la première option du select. Cela rend la navigation au clavier impossible sur firefox.
> 🐛 fix(select): correction option par défaut & navigation clavier [DSFR-63]

- package.json
- Pour réduire le poids du package @gouvfr/dsfr, storybook n'est plus exporté
> ✨ build(release): retrait de storybook dans la release [DSFR-58]

- src/dsfr/core/script/assess/assess-file.js
- Ajouts de messages d'erreurs dans la console en fonction du type d'erreurs retourné par le fetch du fichier à télécharger
- Si le fichier est inaccessible (erreur 500), la fonction assess-file retourne au moins l'extension du fichier.
> ✨ feat(core): assess file error detection [DSFR-28]

- src/dsfr/component/toggle/template/stories/toggle.stories.js
- src/dsfr/core/script/api/modules/register/focus-manager.js
- correction mineure du lint et du legacy js
> 🐛 fix: lint & es5 export

- src/dsfr/component/form/style/module/_fieldset.scss
- Corrige l'alignement des champs en ligne lorsque le nombre de lignes des labels est différent.
> 🐛 fix(fieldset): aligne les inputs inline

- src/dsfr/core/style/action/module/_enlarge.scss
- Correction du background d'un élément d'action étendu au hover. Permet de surcharger le background du a ou button.
> 🐛 fix(core): enlarge link background hover

- src/dsfr/component/accordion/example/index.ejs
- src/dsfr/component/accordion/example/sample/accordions-group.ejs
- src/dsfr/component/accordion/template/ejs/accordion.ejs
- src/dsfr/component/sidemenu/example/sample/sidemenu.ejs
- src/dsfr/component/sidemenu/template/ejs/sidemenu-menu.ejs
- Ajout de la classe `fr-collapse--expanded` en html, sur les collapse ouverts par défaut, pour éviter l'ouverture après le chargement du js.
- Ajout d'exemples d'accordéon et sidemenu avec collapses ouverts au chargement
> 🐛 fix(sidemenu, accordion): collapses ouverts au chargement [DSFR-96]

- README.md
- Correction coquille dans le readme
> 📝 docs(readme): Typo dans le README `utility.scss` => `utility.css`

- dsfr-sb/.storybook/preview.css
- src/dsfr/component/button/template/ejs/button.ejs
- src/dsfr/component/button/template/stories/button-arg-types.js
- src/dsfr/core/template/ejs/action/action.ejs
- Correction de la propriété "type" sur le composant bouton
- Correction de la hauteur de l'exemple modal avec footer
- Retrait du blocage du scroll à l'ouverture d'une modale.
> 🐛 fix(storybook): propriété type du bouton et retrait blocage scroll modal [DSFR-85]

- src/dsfr/component/header/script/header/header-modal.js
- src/dsfr/component/modal/script/modal/modal.js
- Lorsque le header est désactivé en desktop, le js de header retire l'aria-label de la modal car inutile. Le message d'avertissement dans la console indique alors que la modal ne contient pas d'attribut aria. Cette vérification ne doit être faite que si la modale est active. https://github.com/GouvernementFR/dsfr/issues/1120
> 🐛 fix(modal): correction warning header

- src/dsfr/analytics/script/integration/core/actionee.js
- Ajout de la possibilité d'envoyer l'action d'un élément actionee en js via la méthode act().
exemple : 
`dsfr(element).buttonActionnee.act();`
`dsfr(element).buttonActionnee.act({objet de données supplémentaires});`
> ✨ feat(analytics): ajout proxy méthode actionee act() [DSFR-95]

- src/dsfr/component/tooltip/script/tooltip/tooltip-referent.js
- Corrige le retour du focus lorsque l'on ferme le tooltip via la touche échap. Problème constaté notamment au sein d'une modale.
> 🐛 fix(tooltip): placement du focus a la fermeture clavier

- src/dsfr/component/navigation/style/module/_default.scss
- src/dsfr/component/navigation/style/scheme/_default.scss
- Correction de la bordure du menu mobile lorsqu'il ne contient qu'un seul élément #1170
> 🐛 fix(navigation): correction bordure navigation mobile avec 1 seul item

- src/dsfr/layout/pattern/forms/_part/doc/index.md
J'ai modifié le texte suivant : 
> *Présenter* en fin de formulaire, les boutons peuvent être alignés :
en 
> *Présentés* en fin de formulaire, les boutons peuvent être alignés :
> docs: faute d'orthographe

- src/dsfr/component/toggle/style/_print.scss
- Retire une propriété CSS non conforme et inutile dans print.scss #1264
> :bug: fix(toggle): retrait css non conforme dans le fichier print

- package.json
- Pour permettre plus de souplesse, les versions de Node acceptées pour build le DSFR sont maintenant `"^20.19.0 || ^22.12.0 || >=24.0.0"`
> ⬆️ chore(Node): Change la version minimale de Node.js

- src/dsfr/component/tab/script/tab/tabs-group.js
- src/dsfr/component/tab/style/_scheme.scss
- src/dsfr/component/tab/style/module/_default.scss
- Corrige le fond transparent du panel #1300 
- Corrige la hauteur du panel (4px en trop)
> 🐛 fix(tab): ajoute un fond blanc au tab panel
